### ISSUE TITLE
Can the images slide vertically?

### ISSUE THREAD

**Issue by Prufrock1** [nicinabox/superslides#10]
from top to bottom instead of side to side. just wondering if there was a configuration for that

**Comment by nicinabox** [comment]
Currently, no. But it would be easy to add support for that.

**Comment by teiknadi** [comment]
Hi, what is the progress on this task? The entire script is great, but I am really missing this feature.

**Comment by des1001** [comment]
Replace lines from 295 to 352, as quick fix - it should be moved to setting.     

Code: 
https://gist.github.com/des1001/5923227

**Comment by nicinabox** [comment]
0.6.0 let's you add custom animations effects. Refer to examples for adding your own.

**Comment by danilopolani** [comment]
Has someone implemented the vertical scroll with the FX?
