### ISSUE TITLE
jerk in slideshow.?

### ISSUE THREAD

**Issue by jayeshjain24** [nicinabox/superslides#103]
when pagination buttons are clicked,what happens is 80% of the slide gets the smooth animation that I desire,but for the rest 20% it totally destroys the animation by sudden burst of acceleration and then its completion.This does not look good and spoils the user experience.And also I want the width of images to be around 60% of the window width and to be placed at the center.How can these things be achieved??

**Comment by jayeshjain24** [comment]
I got the solution.You just have to add some values to offset!!!thats it

**Comment by kedman1234** [comment]
Will you please give an example to have we add offset in the code does it part of JS or i need to add in CSS
