### ISSUE TITLE
Loading slides via ajax

### ISSUE THREAD

**Issue by jone-rocks** [nicinabox/superslides#104]
Hi,

first of all: thanks for the nice plugin!

My problem:
I'm desperate trying to load slides from a .php-file.
My recent try was to load this content of the .php-file:

<li>< img src="/random-image.jpg" alt="Random Image"></li>
<li>< img src="/random-image.jpg" alt="Random Image"></li>
<li>< img src="/random-image.jpg" alt="Random Image"></li>

... into the ".slides-container"-div with the following JQuery-code:

$(document).ready(function() {
$("a").click(function(event){
$.post('http://localhost/wordpress/wp-content/themes/tablet-test/bg-slides.php', function(data) $('.slides-container').html(data); });
$('#slides').superslides('update');
});
});

The result is, that the ".slides-container"-div get's loaded with an empty li.

Any thoughts on that?

Appreciate your help!

Regards,
JR

**Comment by nicinabox** [comment]
Try with the latest release of 0.6. This should definitely work. You'll want to load in markup that matches your existing slides (so if you're using li's, be sure that's part of what you load).

**Comment by whataboutchris** [comment]
@jone-rocks Did you ever get this to work? I'm in interested.
