### ISSUE TITLE
How to change options?

### ISSUE THREAD

**Issue by fabyeah** [nicinabox/superslides#106]
First, let me say that superslides is a great plugin. Thank you! I searched around and this is the best one for full screen images imho. 

I can't seem to change the options. I try to change slide_speed and slide_easing, but it doesn't work changing it in the superslides.js directly or putting it in another script file like in the demo... 

example: 

  $('#slides').superslides({
    slide_easing: 'easeOutBounce',
    slide_speed: 400,
    pagination: true,
    hashchange: true,
    scrollable: true
  });

What am I doing wrong?

**Comment by nicinabox** [comment]
I don't see anything wrong with that bit of code. Could you link to your source?

**Comment by fabyeah** [comment]
I'm using the 0.5.2 release. 
I'm guessing it only works with the current master branch?

**Comment by nicinabox** [comment]
No that should work fine. It would be helpful to see your code for debugging though.

**Comment by saxisme** [comment]
@fabyeah I had the same problem while integrating in Wordpress, at the end I just had to fix the order the js files were called with the call to jquery as first in the head section.

**Comment by nicinabox** [comment]
Yeah, order definitely matters. Include dependencies before you use them!

This doesn't seem like an issue with the plugin so I'm closing for now.

**Comment by fabyeah** [comment]
Sorry for the late reply.

My mistake. I didn't notice that I loaded application.js (which sets easing and speed) in my scripts. So changing the options before (in superslides.js) or after (in my own main.js) didn't overwrite it. 
FIXED!
