### ISSUE TITLE
An API event when a transition begins, not ends

### ISSUE THREAD

**Issue by ghost** [nicinabox/superslides#109]
The animated.slides event is very useful, but I think there should be two events: one when the transition starts, and one when it completes. animated.slides Occurs when the slide completes. I need an event when the slide starts, so I can fade in a custom caption at the proper time.

Is this possible?

**Comment by ghost** [comment]
A year ago you wrote:

"nicinabox commented a year ago
There is currently an event after slide (slides.animated) that you can bind to.
I could add an additional event before animation begins as well."

Can you still do this?!

**Comment by nicinabox** [comment]
Agreed. Let's make this happen.

**Comment by ghost** [comment]
Yes, please! I love the API, and this would really round it out.

**Comment by nicinabox** [comment]
This is now a part of 0.6. Cheers!

**Comment by ghost** [comment]
Thanks! Can you please provide documentation? Not sure exactly how to use it, yet...

**Comment by nicinabox** [comment]
Yes, I updated the readme. Bind to it the same as other events (the event is `animating.slides`)

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
$('#slides').superslides('current'); doesnt seem to work like it did in the last verion when placed within animating.slides or animating.slides. For instance, this outputs [object Object] when it used to output the index value of the slide being shown. The following should show me 0, 1,2,3 etc, not an object, correct?

$(document).on('animating.slides', function() {
        console.log("current Slide" + $('#slides').superslides('current'));
});

**Comment by nicinabox** [comment]
Beta software. Things might not work as expected :P

You can still get the current by doing something like `$('#slides').data('superslides').current`

**Comment by ghost** [comment]
$('#slides').data('superslides').current works great with animated.slides but leads to unexpected results with animating.slides

The index values are incorrect when manually controlling the slider.

**Comment by nicinabox** [comment]
Remember, this is before animating, so current,  next, and prev will not have been updated yet. What is your expectation for what current should be? The outgoing slide, or the upcoming slide?

**Comment by ghost** [comment]
I basically need the index value of the slide we are animating TO, and then I want to use that index value to fadeIn a div with a class of the same value. That way, I can fade In custom captions for the current slide.

I want to use animating.slides to the transition can happen during the slide, not after.

Current should be the upcoming slide, regardless of whether I am using animated or animating. Thoughts?

**Comment by nicinabox** [comment]
Okay, I haven't tested this, but it should work. I moved the event trigger down a bit and passed in the orientation hash. On your listener, do this and see if you get some values you need (grab the latest off master):

``` javascript
$(document).on('animating.slides', function(e, orientation) {
  console.log(orientation)
});
```

**Comment by ghost** [comment]
Yes it seems the upcoming_slide is giving the value that I need, thanks!

**Comment by nicinabox** [comment]
Killer

**Comment by ghost** [comment]
This script is great!

**Comment by drivebass** [comment]
https://github.com/nicinabox/superslides/issues/146
