### ISSUE TITLE
Last slide event

### ISSUE THREAD

**Issue by parindam** [nicinabox/superslides#11]
Hi,

This is more of a question and not an issue.
Is there any way I can get an event when the last slide ends , something like 'afterEnd' or 'beforeStart' ?

or, can I get the current running slide number ?

**Comment by nicinabox** [comment]
In short, sort of. 

After each animation an event is triggered: `slides.animated`. This even carries 3 variables: the current slide, the next slide, and the previous slide.

Try something like this:

```
$(document).on('slides.animated', function(current, next, prev) {
  if (slides.length === prev) {
    // last slide
  }
})
```

**Comment by parindam** [comment]
This is great. I think it'll help. will try this out.
Thank you a lot for your quick response.

On Tue, Sep 18, 2012 at 6:13 AM, Nic Aitch notifications@github.com wrote:

> In short, sort of.
> 
> After each animation an event is triggered: slides.animated. This even
> carries 3 variables: the current slide, the next slide, and the previous
> slide.
> 
> Try something like this:
> 
> $(document).on('slides.animated', function(current, next, prev) {
>   if (slides.length === prev) {
>     // last slide
>   }
> })
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/nicinabox/superslides/issues/11#issuecomment-8636052.

## 

Thanks,
Arindam.

**Comment by mikemelchiot** [comment]
Where should I put this? 

Thanks

**Comment by nicinabox** [comment]
Probably around where you call superslides.
