### ISSUE TITLE
Update Callback

### ISSUE THREAD

**Issue by mxmtsk** [nicinabox/superslides#110]
Hello,

i find it useful if there would be a callback for the update method. What I'm trying to do is basically to load the next slide via ajax, then update superslides and then slide to the next slide (which is the loaded one) but the animation is false (jumps around and then ends at the loaded slide)

```
$.get(link, function(data) {

  $('.slides-container').append('<li class="form_2"><div class="container">' + data + '</div></li>');
  $('#slides').superslides('update');
  $('#slides').superslides('animate', 'next');



});
```

**Comment by nicinabox** [comment]
`update` is a synchronous method, so a callback is unnecessary. If there is an issue going to the next slide after update, then that should be addressed.

**Comment by mxmtsk** [comment]
Well, then there's an error with the animation. The animation looks like it first jumps back to the slide before the current one (as the current one is the first one in my case i see a white screen) and then it animates to the next one.

**Comment by nicinabox** [comment]
Cool, I'll have a look at, thanks.

**Comment by mxmtsk** [comment]
Do you already have an update on this? :)

**Comment by nicinabox** [comment]
Working on this now.

**Comment by nicinabox** [comment]
This is now fixed in 0.6.0-beta2 (on master).

**Comment by mxmtsk** [comment]
Thank you very much. The current slide disappears while the animation slides to the loaded one. Is this a technical limitation or is there a possibility to fix it?

**Comment by nicinabox** [comment]
Hmm what browser?

**Comment by mxmtsk** [comment]
Chrome, latest version

**Comment by nicinabox** [comment]
Here's what I'm doing to add a slide and I'm not seeing any weirdness:

``` javascript
$('#slides .slides-container').append('<img src="//lorempixel.com/1000/1000" />'); 
$('#slides').superslides('update');
```

As soon as I add `animate` into the mix I see the new slide as blank. It looks like the image hasn't yet loaded. What if you setTimeout for 500ms?
