### ISSUE TITLE
Slides are shown at 50% from top

### ISSUE THREAD

**Issue by niquedegraaff** [nicinabox/superslides#112]
This is kinda weird. The problem is that when i refresh the page the img in the slides have a css TOP setting of: 477.5px. Why? It is not happening when when i just load the page from the url bar (so when i'm not not refreshing). It also appears to be happening randomly when i switch pages (click on other page link, and then click on the home link). I'm pulling my hears out.. because i can't figure out what is causing it.

When landing on the page:
![Screenshot 2](http://imageshack.us/a/img196/1880/54q.png)

After Refreshing the page:
![Screenshot 1](http://imageshack.us/a/img827/6010/lb3c.png)

You can view it live (for as long my server is up) at:
http://82.72.108.59/

**Comment by ghost** [comment]
I am having this issue as well!

**Comment by elisafern12** [comment]
Same here! When i refresh normally, (press ctl R), the slide shows at 50% but when I refresh by pressing ENTER in the URL bar or that I just resize a bit my browser, the image resize correctly to fullscreen. I am using the beta 0.6 version with the fade. I doesn't do it with the demo, but when I did a simple implementation I did that.

Thank you for any feedback on this issue.

**Comment by niquedegraaff** [comment]
It has been fixed. Use the new master tree download. You will be happy!

**Comment by nicinabox** [comment]
This is a side effect of images not being fully loaded. 

Previously on 0.6.0 you needed to call superslides after onload instead of onready to get around this. A few days ago I fixed it so you can use onready :)
