### ISSUE TITLE
api doesn't work on ie8

### ISSUE THREAD

**Issue by ergec** [nicinabox/superslides#116]
I'm having issues to make api work in ie8

$('#slides').superslides('animate', "prev");

works on chrome ie9 but not in ie8 . I also tried

$('#slides').superslides("prev");

but this doesn't work too

**Comment by nicinabox** [comment]
Hmm, it definitely works in all those browsers. Are you using an element with an id of `slides`?

There is a error in the documentation I need to fix: `.superslides('prev')` does not move the slider. Instead it returns the index of the previous slide.

**Comment by ergec** [comment]
Hi sorry it's my bad. It was something else causing trouble. I deleted my
question on stackoverflow.com but forgot on github. Except some minor stuff
it works great. Simple but better than most of the sliders. Great work.

**Comment by nicinabox** [comment]
Great! Closing this then.
