### ISSUE TITLE
Loading of slides / PULSE

### ISSUE THREAD

**Issue by deluxtrade** [nicinabox/superslides#118]
First of all many thanks for fantastic work! I would like to ask about circle between loading images. Here in the DEMO: http://nicinabox.com/superslides/ after images are loaded it dissapears. On my site it is shown permanently. Sorry for maybe stupid question but I am a newbie. Is it needed to set something special in the code below or somewhere else? Thank you for you support.The site I am talking about is here: http://deluxtrade.com/demo3/examples/simple.html

```
<div class="loading-container">
<div class="pulse"></div>
```

  </div>

**Comment by nicinabox** [comment]
You need to hide or remove it after initialization:

``` javascript
  $(document).on('init.slides', function() {
    $('.loading-container').fadeOut(function() {
      $(this).remove();
    });
  });
```
