### ISSUE TITLE
issue with having more than one image on each slide

### ISSUE THREAD

**Issue by enrikpavdeja** [nicinabox/superslides#120]
Hi there, 

I've started utilising this on a website I am building and it's absolutely amazing! I've run into a serious problem which I think might be a bug in the way the css is being overwritten in the javascript. 

I'm trying to add another image inside of a smaller div on the corner of each slide. I then use css to change the way the image is formatted onto the background image so that it fills its own div at width 100%, which doesn't do anything. 

As far as I can tell, the css is being overwritten in the javascript where I assume you're referencing spans of 'img' to change the width and height of the background image, which in turn is having an effect on every image on the slide. 

Is there a way to localise this so that we can add as many images onto the slide as we like, while still keeping the background image the same size as the window? I think this would be a very useful thing to have working on here. 

Keep up the awesome work and many thanks!
Enrik

It's these lines here that I think are the offenders. 

```
images: function () {
            var $images = that.$container.find('img')
                .not(that.options.elements.preserve)

            $images.removeAttr('width').removeAttr('height')
                .css({
                "-webkit-backface-visibility": 'hidden',
                "-ms-interpolation-mode": 'bicubic',
                "position": 'absolute',
                "left": '0',
                "top": '0',
                "z-index": '-1',
                "max-width": 'none'
            });

            $images.each(function () {
                var image_aspect_ratio = that.image._aspectRatio(this),
                    image = this;

                if (!$.data(this, 'processed')) {
                    var img = new Image();
                    img.onload = function () {
                        that.image._scale(image, image_aspect_ratio);
                        that.image._center(image, image_aspect_ratio);
                        $.data(image, 'processed', true);
                    };
                    img.src = this.src;

                } else {
                    that.image._scale(image, image_aspect_ratio);
                    that.image._center(image, image_aspect_ratio);
                }
            });
        },
```

**Comment by nicinabox** [comment]
Have you tried using `.preserve` on the images you don't want resized?

**Comment by enrikpavdeja** [comment]
Ah! Silly me! That worked!

Thanks!!
