### ISSUE TITLE
How to reset timer on prev and next

### ISSUE THREAD

**Issue by ergec** [nicinabox/superslides#125]
I use $('#slides').superslides('animate', "prev"); and next on my custom arrows for navigation. I set timer to 5 seconds for auto-play. But if I click let say next at 4th second next slide appears after a second. How can I reset timer manually so on every animate prev next, timer will reset to 5 seconds again.

**Comment by nicinabox** [comment]
Ah this is a bug. The timer should reset after any user action.

**Comment by nicinabox** [comment]
Oh sorry, I didn't realize you were using custom navigation. You just need to call `stop` before animate.

``` javascript
$('#slides').superslides('stop');
```

**Comment by slavajacobson** [comment]
Calling stop will disable the autoplay.

This solves it:
            $(this).superslides('stop');
            $(this).superslides('animate', 'prev');
            $(this).superslides('start');
