### ISSUE TITLE
Hash in url

### ISSUE THREAD

**Issue by foxer-zt** [nicinabox/superslides#126]
Hello!
 Please, told me how to remove hash from url. I'm configuring Wordpress theme and all links on site doesn't work. I think the problem in hash in url because when I write link's href directly in url input everything works good.

**Comment by fabyeah** [comment]
Set hashchange to false:

```
// Set Superslides options
  $('#slides').superslides({
    slide_easing: 'easeInOutCubic',
    slide_speed: 800,
    pagination: true,
    hashchange: false,      
  });
```

**Comment by robinwkurtz** [comment]
This does not work for me personally.. changed in application.js and superslider.js.

Thanks,

**Comment by foxer-zt** [comment]
Actually it helped, thanx.
