### ISSUE TITLE
portret photo's with perserve

### ISSUE THREAD

**Issue by jlentink** [nicinabox/superslides#133]
Hi,

When i add a slide with preserve ratio in portet mode it does not align to centre.

**Comment by nicinabox** [comment]
Images with `.preserve` are mostly ignored. There is no letterboxing in the plugin.

**Comment by jlentink** [comment]
what is the easiest way to occomplish that the .preserve images are getting aligned in the center?

**Comment by nicinabox** [comment]
Use css

**Comment by marioosh-net** [comment]
This works for me. Anyway thanks for nice slider ;)

```
 .preserve {
     margin: auto;
     display: block;
 }
```
