### ISSUE TITLE
Using media queries doesn't work with inherit_height_from

### ISSUE THREAD

**Issue by neridev** [nicinabox/superslides#137]
Hi, first of all, thank you for superslides - its perfect! Here is my question, I use inherit_height_from with selector:
.... animation_easing: 'swing',
     inherit_height_from: slider_wrap,
     ....
});

Default #slider_wrap have height: 300px , and in css I have used media queries for this selector, height: 250px, but superslides javascript code completely unresponsive for this change. Please, It's there any way how solution this problem?

Thank you!

**Comment by nicinabox** [comment]
`inherit_height_from` should be a CSS selector string. 

```
inherit_height_from: '#slider_wrap'
```
