### ISSUE TITLE
slide won't stop

### ISSUE THREAD

**Issue by medafighterX** [nicinabox/superslides#14]
how do I disable the autoplay?

**Comment by nicinabox** [comment]
Play is off by default. All [configurable options](https://github.com/nicinabox/superslides#options) are listed in the readme. Are you using the latest version (0.4.2)?

**Comment by medafighterX** [comment]
Not sure. But I'm pretty sure I've downloaded the latest version. Anyway, I already fixed the problem. Turns out that I just have to set the play to pause on the application.js file, which I wasn't able to check before. Sorry to bother you guys.

**Comment by nicinabox** [comment]
`play: false` is the default option. Let me know if you are having issues without specifying anything.
