### ISSUE TITLE
html5 <video> doesn't start

### ISSUE THREAD

**Issue by nazenazenaze** [nicinabox/superslides#148]
Hello all,

First, thanks a lot for this amazing script (really smooth).

I try to insert a <video> in my slides but the video doesn't start.

<div id="slides">
<ul class="slides-container">
<li>

 <video autoplay="autoplay" id="spot" loop="loop">
     <source src="https://www.numbrs.com/assets/numbrs-video-951b63a93943139627155c7de1d8cb86.mp4">
     <source src="https://www.numbrs.com/assets/numbrs-video-770768d21d5caf7c1f7f44cefa5ca304.ogv">
</video>

</li>
</ul>
</div>

The video is correctly show but don't start.

When i delete <ul class="slides-container"> & </li> the video is correctly playing but there is no more slides...

I have the latest version of superslides.

If you have an idea don't hesitate.

Best & thanks again.

Anthony

**Comment by nicinabox** [comment]
Can you share your code?

**Comment by nazenazenaze** [comment]
You can check it out just here > http://laddereditions.com/1/superslides/examples/test.html

**Comment by nazenazenaze** [comment]
i've found a solution.

i start my video after (i think) superslides script be initialized.

here is my javascript code at the bottom of my page >

 <script type = "text/javascript">

 setTimeout(function() {
var video1 = document.getElementById('video1') ;

function playVideo()
{
video1.play() ;
}

video1.onload = playVideo() ;}, 50);

</script>
