### ISSUE TITLE
Any way to add a fade effect?

### ISSUE THREAD

**Issue by Missyc** [nicinabox/superslides#15]
Love the full screen image size and performance of this slider...I just need it to fade to the next slide

Any way to add a fade effect? I know both the easing and animate plugins support it, just not sure how to incorporate it in superslides. I am not super experienced with jQuery but if you outline the basics of how it could be done...I should be able to get there ; )

**Comment by nicinabox** [comment]
Thanks for the compliments :)

Historically I've referred users to to [Backstretch](http://srobbin.com/jquery-plugins/backstretch/) for fullscreen fade, but it doen't handle additional blocks of content inside each "slide". Maybe it's time to add some new animation effects.

**Comment by Missyc** [comment]
I would love that! I am integrating into WordPress so I pull custom post title / excerpt / links into the content block. So that is a definite plus for superslides and a must for me.

**Comment by nicinabox** [comment]
In 0.5.0 I'm adding an animation engine that will hand different effects such as this and vertical sliding as in #10. This is in the works now.

**Comment by axelwehner** [comment]
Hi Nic, thanks for this really nice plugin. Is vertical sliding in v0.5.1 possible? I couldn't find any sample or documentation about it. Thanks!

**Comment by nicinabox** [comment]
Thank you. Unfortunately I didn't have enough time to get the new effects in with the release today. I've setup the code for it though, and it's the next thing I'm working on. Assuming there are no other critical bugs, it should be in the next version.

**Comment by nicinabox** [comment]
Added in 0.6.0. Currently on master.
