### ISSUE TITLE
Removing navigation when slider ends

### ISSUE THREAD

**Issue by a0r1an** [nicinabox/superslides#151]
I know there is a way to listen for the animation to end I just don't know how to implement it. I want to remove the "Next" navigation element when the slider ends.
Any help would be appreciated.

**Comment by fabyeah** [comment]
+1

seconded.
Please include an option to deactivate carousel / infinite loop.

**Comment by BergkampHUN** [comment]
+1
It would be great!

**Comment by nicinabox** [comment]
Just call hide or remove on that element?

**Comment by fabyeah** [comment]
You also need to unbind the keyboard navigation.

**Comment by bytoz** [comment]
just about the keybord unbind you ca easily implement in this way:
in jquery.superslides.js add option at row ~15:
(without the '<>')

  this.options = $.extend({
    play: false,
    animation_speed: 600,
    animation_easing: 'swing',
    animation: 'slide',
    inherit_width_from: window,
    inherit_height_from: window,
    >>>>usekeyboard: true,<<<<
    pagination: true,
    hashchange: false,
    scrollable: true,
    elements: {
      preserve: '.preserve',
      nav: '.slides-navigation',
      container: '.slides-container',
      pagination: '.slides-pagination'
    }

and then at row ~54 change
    $(document).on('keyup', function(e) {
        if (e.keyCode === 37) {
          that.animate('prev');
        }
        if (e.keyCode === 39) {
          that.animate('next');
        }
    });
to
    $(document).on('keyup', function(e) {
      if (that.options.usekeyboard){
        if (e.keyCode === 37) {
          that.animate('prev');
        }
        if (e.keyCode === 39) {
          that.animate('next');
        }
      }
    });

**Comment by bytoz** [comment]
...so now you can add option usekayboard:true/false to the superslide call in your js
