### ISSUE TITLE
Fade In-Out Caption

### ISSUE THREAD

**Issue by fikriw** [nicinabox/superslides#154]
Hi Nic, thanks for this great plugin. Can we add effect for the caption text to fade in/out the the slide move? 

Thanks

**Comment by nicinabox** [comment]
Use the API events to control effects on content.

**Comment by fikriw** [comment]
Dear Nic,

I try using event like this, but it only fade in at the 2nd slide, can you
please help. Thanks

Demo : http://lookcircle.com/new2/index2.php
*
*
_JS:_
_------------------------------------------------------------------_
$(".slides_caption").hide();
$(document).on('animated.slides', function() {
 $(".slides_caption").fadeIn("slow");
});
_------------------------------------------------------------------_
*
*
*
*
_HTML :_
_------------------------------------------------------------------_*
*

<div id="slider">
<div id="slides">
 <ul class="slides-container">
  <li>
<img src="./images/bg1.jpg" alt="">
 <div class="slides_caption">
  <h1>INTERIOR</h1>
</div>

  </li>
  <li>
<img src="./images/bg1.jpg" alt="">
 <div class="slides_caption">
  <h1>ARCHITECTURE</h1>
</div>
  </li>
</ul>

</div>
 </div>

On Sat, Sep 14, 2013 at 4:42 AM, Nic Aitch notifications@github.com wrote:

> Use the API events to control effects on content.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nicinabox/superslides/issues/154#issuecomment-24426676
> .

## 

Regards,
Fikri Wirawan

**Comment by ahmadajmi** [comment]
@fikriw Hi fikriw,

Try this code as it solved my issue

``` javascript
function slideAnimation(element, animation){
        $element = $(element);
        $(document).on('animated.slides',
            function() {
                $element.addClass('animated ' + animation);   
                window.setTimeout( function(){
                    $element.removeClass('animated');
                }, 1000);       
            }
        );
    }

slideAnimation('.slides-inner', 'fadeInRightBig');
```
