### ISSUE TITLE
Using with animate.css

### ISSUE THREAD

**Issue by ahmadajmi** [nicinabox/superslides#158]
Hi,

Trying to add [Animate.css](http://daneden.me/animate/) support.

``` javascript
$(document).on('animated.slides', function() {
     $('.slides-inner').addClass('animated fadeInRightBig');
});

```

This is the [Demo](http://ontwik.com/now/new/) for the current state 
It works fine on first slides, but when slides end I repeat the slides again nothing happens. How can I fire this on every iteration of the slides.

Thanks

**Comment by ahmadajmi** [comment]
I solved this issue with this code.

``` javascript
function slideAnimation(element, animation){
        $element = $(element);
        $(document).on('animated.slides',
            function() {
                $element.addClass('animated ' + animation);   
                window.setTimeout( function(){
                    $element.removeClass('animated');
                }, 1000);       
            }
        );
    }

slideAnimation('.slides-inner', 'fadeInRightBig');
```

**Comment by macsupport** [comment]
Tried your code but not seeing any animate.css animations. Any chance to see your demo?

**Comment by ahmadajmi** [comment]
@macsupport This is a [demo](http://ontwik.com/foo/now/), you need to include [animate.css](http://daneden.me/animate/) first

**Comment by Prokophs** [comment]
Hi ahmadajmi,

Is there a demo to see how to use this code (codepen, fiddle)?
I'm not a javascript expert and would be really appreciated to learn how to implement custom animations on superslides as the easing option isn't working.

Thanks in advance.

**Comment by ahmadajmi** [comment]
Hi @Prokophs 

I'm very happy to found the demo code as it was from 2013, I pushed all the working template [here](https://github.com/ahmadajmi/html-template) and this is the [JS](https://github.com/ahmadajmi/html-template/blob/master/_include/js/main.js#L33) code for doing the animation.

Hope this helps :)

**Comment by Prokophs** [comment]
Hi ahmadajmi,

I've seen your template and it is really cool.
But what I actually wanted to achieve it was using animate css on the slide fx and not on the caption.
What I want to do really is the following transition effect:

http://tympanus.net/Development/PageTransitions/
"Different Easing"

That would be awesome if you could help as I'm not a javascript expert.

Thanks in advance.
