### ISSUE TITLE
issues / problems IE8 touchable hammer.js

### ISSUE THREAD

**Issue by dev0null0** [nicinabox/superslides#163]
When I implemented superslides using hammer.js for touch screen functionality everything stoped working in IE8 (not tested other IE versions).

I tried editing css and js but nothing seems to help but giving up scrollability and touch functions.

**Comment by dev0null0** [comment]
Hooray!
Solution: use jquery version of hammer.js available here: 
https://github.com/EightMedia/hammer.js/blob/v1.0.5/dist/jquery.hammer.js

**Comment by invamped** [comment]
Hi, I'm having the same issue with IE8. How did you go about fixing it? I've tried using the linked version of hammer. cheers

**Comment by dev0null0** [comment]
ie8 is dead
