### ISSUE TITLE
Prevent cropping on certain image size

### ISSUE THREAD

**Issue by teo10** [nicinabox/superslides#168]
All my slide images are 1920x1080px.
But when check the images on Supeslider on 1920x1080 monitor, I notice they are all cropped in height.

Is it possible to set a default width and height (1920x1080) for the Superslides so that the images don't get cropped?

**Comment by nicinabox** [comment]
Have you taken into account browser chrome?

**Comment by teo10** [comment]
Thanks, 
I was just wondering that how can I set the max-height / width to the slide images so that they don't get cropped on desktop devices?

**Comment by nicinabox** [comment]
Sorry, this is not possible. The images would need to be letterboxed in theory.
