### ISSUE TITLE
Second instance does not initialize

### ISSUE THREAD

**Issue by darkoromanov** [nicinabox/superslides#17]
I have two superslides instances in a page (why two? the first one is the background of the page, the second one is a fullscreen gallery) and I detected this problem:

when I make the second call: 

$('#slides').superslides({
                        play: false,
                        slide_easing: 'linear',
                        nav_class: 'slides-navigation',
                        container_class: 'slides-container',
                        pagination: false,
                        hashchange: true
                    });

the initialization never happens, because the event:

$('body').on('slides.initialized', '#slides', function () {....});

is never called, but worst is the superslides doesn't appear. The weird is that the animated event is fired.

The other superslides is $('#backslides') so I'm sure it's not called again in the same node.

**Comment by darkoromanov** [comment]
I hacked it a little, commenting line 251, now it works but with odd behaviours (it appears a scrollbar, the slide is very very slow....).

EDIT:  ok, looking at the code I see that it can never be used with more than one instance, now I'm in trouble :-(

**Comment by nicinabox** [comment]
Hmm, yeah I hadn't considered this use case. Is the gallery something that initializes when you click on it or something?

**Comment by darkoromanov** [comment]
yeah, the first gallery acts as a navigation system for the site, so each LI contains a page, inside of one of these pages I should launch a fullscreen photo gallery by clicking a link.

**Comment by nicinabox** [comment]
Perfect. I'll try to work on a solution for multiple instances this weekend.

**Comment by darkoromanov** [comment]
Thanks a lot... my customer's crying like a baby to have it (just crazy...).

**Comment by nicinabox** [comment]
Damn clients :P

**Comment by nicinabox** [comment]
I looked into adding this quickly to the next release, but it's trickier than I thought. I've scheduled it for 0.5.0, which is in the works now.

**Comment by darkoromanov** [comment]
Thanks

**Comment by nicinabox** [comment]
Multiple instances are now supported in 0.5.0. Shooting to release officially in the next few days. If you'd like, grab the code from 0.5-wip and try it out.
