### ISSUE TITLE
Use <section> as slide?

### ISSUE THREAD

**Issue by th3lonius** [nicinabox/superslides#172]
I am trying to create a horizontal-scrolling single page site with <section>'s set to full window width/height. This plugin seemed like it would make this easy, but I can't get it to work. Is it programmed to handle unordered lists and <div>s only?

**Comment by nicinabox** [comment]
Hmm, this plugin doesn't do "scrolling" in the classic sense. `section` tags should work fine providing you follow the parent-child structure like a `ul`.
