### ISSUE TITLE
Image resize delay?

### ISSUE THREAD

**Issue by swhitt24** [nicinabox/superslides#175]
There seems to be a brief showing of background on the right side of the slider when resizing. Much like the image is not resizing as quickly as the container.  This is seen in the demos as well in my own site. Is there a fix?

**Comment by nicinabox** [comment]
This is normal. There is a 200ms delay on the resize even to avoid excessive repaints. Js based resizing will never match the performance of the equivalent CSS.

**Comment by swhitt24** [comment]
Ok, but how to plugins like backstretch for example (http://srobbin.com/jquery-plugins/backstretch/) achieve resizing that does not cause the delay? Is it something to do with the difference in using the image tag as opposed to background image. Sorry, I am still new to writing js so I am trying to understand why there is a difference. 

Thanks
