### ISSUE TITLE
Individual slide delay

### ISSUE THREAD

**Issue by nafens** [nicinabox/superslides#178]
I know that you can use the 'play' option in order to set a time in milliseconds before progressing to the next slide automatically. This sets a global time for the entire slideshow.

What I would like to achieve is for individual slides to have their own specific progress/delay time. 
For example if I have a slideshow with twenty slides I want all the slides to progress automatically and to stay on screen for 5 seconds. However the third slide should be displayed for 20 seconds.

I have tried to do this by using the animated.slides event but I cant get it to work as the animation stops with the fourth slide :

Here is my code:

```
  $(function () {
      $('#slides').superslides({

          hashchange: true,
          play: 5000,
          pagination: true
      });


  });

  $('#slides').on('animated.slides', function () {
      var current_index = $(this).superslides('current');

      if (current_index === 2) { // third slide

          $(this).superslides('stop');

          var disp = function test1() {

              setTimeout(function ()

                  {
                      $('#slides').superslides('animate', 3)
                  }, 20000);

          }
          disp();

      }

  });
```

Any help would be appreciated.

**Comment by signegb** [comment]
I need to do something very similar. Were you able to figure it out?

**Comment by nafens** [comment]
@signegb 

No, unfortunately not yet.

**Comment by crixon** [comment]
You can do it like this:

```
$('#slides').superslides({
      hashchange: true,
      play: 500,
      pagination: true
  });

$('#slides').on('animated.slides', function () {
    var slideNo = $(this).superslides('current');
    if(slideNo === 2){
        $(this).superslides('stop');
        setTimeout(function(){
            $('#slides').superslides('start')
        }, 2000);
    }
});
```

**Comment by nafens** [comment]
Great,  it works.
