### ISSUE TITLE
Scrolling content

### ISSUE THREAD

**Issue by randalldon** [nicinabox/superslides#18]
Hi there, excellent work on the slider btw.

I saw it mentioned that there is now support for "scrollable content" in Superslides 0.4.1. http://nicinabox.com/blog/superslides-0-dot-4-1-released/. How does this get applied?. My issues is i have a text box that is part of one of the slides that it taller than the browser window but currently i have no ability to scroll this should it be cut off by the browser window height. Can this be implemented via Superslides or is the mention of "scrollable content" relevant to something else entirely?

Many thanks in advance.

**Comment by nicinabox** [comment]
Discussion: http://nicinabox.com/blog/superslides-0-dot-4-1-released/
