### ISSUE TITLE
Single slide

### ISSUE THREAD

**Issue by randalldon** [nicinabox/superslides#19]
I was just wondering if the fix for a single slide has been included in version 0.4.2. Currently, if i only have a single slide, this is completely hidden on page load. The content is output to html but visually i can't see anything. This relates to the closed issue #4.

**Comment by nicinabox** [comment]
Aw crap. Looks like this is back again after a refactor.

**Comment by randalldon** [comment]
Sorry to be the bearer of crap :). Hopefully, as you got this sorted on a previous iteration of superslides, it won't be too much hassle to sort out. Currently i'm using a dummy second slide for the single slide instances and hiding the navigation so it does function for client demo purposes but going forward that's not really practical solution.

I really appreciate all your time on answering my queries.

**Comment by nicinabox** [comment]
I'm glad you brought it up :)

I'll try to release 0.4.3 as a hotfix this evening. As it's coming up on the holiday it's unlikely I'll get another chance until the weekend I think.

**Comment by ironchef1369** [comment]
whenever you get this fix in, I'd appreciate it a ton.  Thanks :)

**Comment by nicinabox** [comment]
I've got it, but I've got to commit and push it. Give me about 30 min

**Comment by nicinabox** [comment]
Okay! Sorry for the delay.

This is fixed in the dev branch. I'm not _quite_ ready to release 0.4.3, but dev is nearly there. It has the fix you need.

**Comment by ironchef1369** [comment]
The fix doesn't seem to be working.  On a single slide it is still hiding the slide completely.  In my case I'm using the ul li example and with a single li it shows display: none.  

It would also be nice if the navigation got hidden when there is only one slide.

**Comment by nicinabox** [comment]
Can you confirm that you are using 1.4.3 from dev branch? Also, if you look at the demo in dev with a single slide, do you see the same results?

**Comment by ironchef1369** [comment]
Ok, I must have downloaded the wrong branch. My apologies.  Seems to be working now!  Thanks for your patience.

**Comment by nicinabox** [comment]
It happens! Just needed to make sure it wasn't something on my side.

**Comment by randalldon** [comment]
Sorry to re-open this but having checked out the dev branch yes the slide does show with a single slide now but the image overflow isn't hidden and so a scrollbar is presented to the height of the image. If using a single slide i need to maintain the hidden aspect and avoid the scrollbars. This behavior occurs in all browsers.

**Comment by nicinabox** [comment]
0.5.0 will have the proper fix for this.

**Comment by kukoman** [comment]
Hi there,
had you the to fix this issue? Or do we have some workaround for this? 
thank you

**Comment by samuel-clara** [comment]
Hi the issue still seems to exist. Is there a possibility to fix it or to write a workaround?
Thank you very much

**Comment by patosG** [comment]
I did have the same issue. I've fixed it adding line 132:

```
  if (that.size() === 1) {
    that.$container.css({
      display: 'none',
      margin: '0',
      padding: '0',
      listStyle: 'none',
      //position: 'relative',
      height: '100%'
    });
  }
  else {
    that.$container.css({
      display: 'none',
      margin: '0',
      padding: '0',
      listStyle: 'none',
      position: 'relative',
      height: '100%'
    });
  }
```
