### ISSUE TITLE
Mobile Problem

### ISSUE THREAD

**Issue by ceehaupt** [nicinabox/superslides#195]
Hi, 
I build a slider with the fade animation and on desktop everythimg is ok, but on mobile only the first image is shown. The fades are shown without the background image.
Thanks.

**Comment by stottsan** [comment]
Hi @ceehaupt.  

When I view your site on an iPhone, the animation seems to be working as expected -- it cycles through all four images and the h1 teaser text changes as well.  Did you fix something, or are you seeing a different result?  If it's still not working for you, let us know what device/OS/etc you're testing with.

I'm new to Superslides, but I'm happy to help if I can.  Thanks!

**Comment by ceehaupt** [comment]
Fixed it. Thanks. Was an image compression problem. Nothing to do with the slider.
