### ISSUE TITLE
Add callback events for beforeSlide and afterSlide

### ISSUE THREAD

**Issue by brandoniffert** [nicinabox/superslides#2]
It would be nice if developers could supply a callback function for before and after slide.

**Comment by nicinabox** [comment]
There is currently an event after slide (`slides.animated`) that you can bind to.

```
$('body').on('slides.animated', function() {
  console.log('slide animated')
}
```

I could add an additional event before animation begins as well.

**Comment by brandoniffert** [comment]
Great. Missed that in the docs. Thanks for the plugin, love how simple it is.

**Comment by nicinabox** [comment]
Woohoo! :)
