### ISSUE TITLE
Further images in panel content

### ISSUE THREAD

**Issue by randalldon** [nicinabox/superslides#20]
I have an issue where if i use an additional image within the slide this gets picked up by Superslides too. Is there a method to only select the first image within any slide li? Currently all images get picked up including one deeper in the content. which should just be presented as normal rather than being picked up as a slide background.

Many thanks in advance.

**Comment by nicinabox** [comment]
Yes, you can add `.keep-original` to any images that you don't want to be resized.

**Comment by randalldon** [comment]
Ahhh - cheers for that. I was looking into only grabbing the first image via jQuery's first() option but the 'not' option is much more elegant.

**Comment by itthename** [comment]
I have the same issue, but what is ".keep-original" and where is it applied? Is it a class?

**Comment by nicinabox** [comment]
Yes, it's a class on the img. In 0.5.0 this was changed to `preserve`. 

`<img class="preserve" />`

**Comment by itthename** [comment]
thanks for the clarification, that did the trick.

On Jan 1, 2013, at 11:19 AM, Nic Aitch wrote:

<img class="preserve" />

**Comment by stefanledin** [comment]
Is there a way to prevent Superslides from appending certain images to the listitem? 
For example, if I write my HTML like this:

``` html
<li>
<div class="content">
<img src="image.jpg" class="preserve">
<p>Content...</p>
</div>
</li>
```

Superslides creates this markup:

``` html
<li>
<img src="image.jpg" class="preserve">
<div class="content">
<p>Content...</p>
</div>
</li>
```
