### ISSUE TITLE
Chrome: some slide are not seen (white screen)

### ISSUE THREAD

**Issue by daseeds** [nicinabox/superslides#201]
Hello,

Got a strange problem I cannot reproduce on the demo, using chrome Version 32.0.1700.107 m.
The slides 4 and 5 remain somewhat hidden (?).
Can be seen at http://dev1.juganville.com/en/bed-and-breakfeast-in-16-century-manor-in-normandy-rooms-la-tour-spacious-and-bright-room-exposed-ceiling-beams#3

If I remove the property -webkit-backface-visibility: hidden; from the img then it seems to solve the problem.
I'm using bootstrap 3.1 and jquery 1.9.1

**Comment by florantara** [comment]
Hello, same happening here. I have 3 slides, and when I turn on the fade effect, after 400 miliseconds aprox, the screen goes white, then if you click on one of the arrows, it goes to the second slide, shows the img, but goes blank again....

I turned off the -webkit-backface-visibility: hidden; from the img, but no luck.

EDIT:  I found that changing - on line 263 - "opacity: 0", to "opacity:1", and - on line 287 - "display:none" for "display:block", solves it.
