### ISSUE TITLE
Last li child redirect link

### ISSUE THREAD

**Issue by leakystudio** [nicinabox/superslides#205]
I would like to have the "next" link of the last slide redirect to another URL; likewise, on the first slide I would like the "prev" link to also redirect. There is a similar question here:
https://github.com/nicinabox/superslides/issues/182 and he has found a solution like this:

var clicked=0;
    $('a.next').on('click', function (e) {
    clicked++;

```
if (clicked >= 3) {
    clicked = 0;
    //$("a.next").attr("href", "http://www.google.com/");
    window.location = "URL GOES HERE";
} else {
    e.preventDefault();
}
```

});
The above works fine, but is not ideal, since it is based on simply clicking the next link more than 3X (regarldess of where one is in the slideshow). In my set-up I'm using the <ul><li></li></ul> formatting. Any tips would be great - thanks!

**Comment by nicinabox** [comment]
Check if the current slide is equal to length - 1. Change the link attr if it is.
