### ISSUE TITLE
Links in Pagination and Navigation not working, not clickable

### ISSUE THREAD

**Issue by WAMH** [nicinabox/superslides#206]
Good day, thanks for a lovely plugin!
I don't know whether my issue stems from a bug, or from something I'd be doing wrong.

I am using superslides on a WordPress install. Testing the slideshow on a static page with static images (in an ul as per the demo). The navigation and pagination links are not detected as such by the mouse (which doesn't change cursor, and doesn't click, even it is impossible to select the links normally by clicking on the text and trying to select that text).

It is as if the links are non existent, but they show, visually, on the page. They are otherwise un-selectable, un-clickable.

I am loading jquery min 1.9.1, superslides min, and the slides are correctly showing full page images, and hitting left and right keys on the keyboard activates the slides very well. The only trouble is with the mouse.

I tried giving very high z-indexes to the nav containers, and the anchors inside the nav containers, to no avail...

I tried removing all BUT the slider container from my page (headers, footers, and other content divs), to test if something else was causing a conflict, same result.

I wonder if someone else experienced the same, and I hope this will have a quick fix (as it is probably something I'm overlooking... No one else had this issue posted here yet...), and a million thanks for reading my problem :)

**Comment by WAMH** [comment]
Here is the code I'm using (stripping all of WP stuff and includes to minimize conflict potential):
It's the minimal structure recommended on the documentation:

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Test SuperSlides</title>
    <link href="http://xx.xx.xxx.xxx/~xxx/wp-content/themes/cf.0.1/style.css" type="text/css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js?ver=1.9.1" type="text/javascript"></script>
    <script src="http://xx.xx.xxx.xxx/~xxx/wp-content/themes/cf.0.1/_s/jquery.superslides.min.js?ver=3.8.1" type="text/javascript"></script>
    <script type="text/javascript">
        $( document ).ready( function(){
            $('#slides').superslides();
        });
    </script>
</head>
<body>

    <div id="slides">
        <ul class="slides-container">
            <li><img src="<?php bloginfo( 'stylesheet_directory' ); ?>/_i/cover-sample.jpg" /></li>
            <li><img src="<?php bloginfo( 'stylesheet_directory' ); ?>/_i/cover-sample.jpg" /></li>
        </ul>
        <nav class="slides-navigation">
            <a href="#" class="next">Next</a>
            <a href="#" class="prev">Previous</a>
        </nav>
    </div>

</body>
</html>
```

**Comment by WAMH** [comment]
FIXED: by removing z-index -1 from #slides in superslides' CSS:

``` css
#slides {
   z-index: -1 // This was causing the nav links to be totally unresponsive on Mac browsers (Safari, Chrome, FF)
}
```

As nobody complained about this anywhere I've read, I suppose this is peculiar to my setup. If so, sorry for the fuss :) if not, or anyone else encounters such issue, I hope this will be found useful.

**Comment by nicinabox** [comment]
Glad you got it resolved
