### ISSUE TITLE
Text disappearing on slide change

### ISSUE THREAD

**Issue by juliangav** [nicinabox/superslides#207]
I have the initial text showing, but it disappears on following slides unless I highlight where the text should be (Chrome 32). http://rpm.thomaswebs.net/enterprise/

Anyone else having this issue?

Julian

**Comment by chrisryu** [comment]
I came across this slider this morning and it looks amazing, but I've just implemented it and have the same issues as Julian - anybody got any ideas on this one?

**Comment by chrisryu** [comment]
Hi Julian - it appears that if you implement the hardware acceleration that they've used in their demo - the issue is resolved.

http://nicinabox.com/superslides/javascripts/jquery.animate-enhanced.min.js

Add that script above the superslide.js file.

Hope this helps

**Comment by juliangav** [comment]
You my friend, deserve a beer. Thank you!

**Comment by WAMH** [comment]
2 beers! ;)
