### ISSUE TITLE
Link to specific tab

### ISSUE THREAD

**Issue by mpolom** [nicinabox/superslides#21]
Hi, is it currently possible to navigate to a specific tab in the slider using an external navigator? Cheers.

**Comment by mpolom** [comment]
Scrap that, edited:

``` javascript
    var $pagination;
    $pagination = $(".slides-pagination");
    if (!(i >= 0)) {
      i = size - 1;
    }
```

to read

``` javascript
    var $pagination;
    $pagination = $(".navigation");
    if (!(i >= 0)) {
      i = size - 1;
    }
```

to match my navigation element, and gave links #0 #1 etc. Would be nice to be able to do this without editing the plugin though!

**Comment by nicinabox** [comment]
I'll make it configurable!

**Comment by mpolom** [comment]
brilliant thanks!
