### ISSUE TITLE
The demos do not appear in firefox 12.0

### ISSUE THREAD

**Issue by indrajitdan** [nicinabox/superslides#22]
http://nicinabox.github.com/superslides/

**Comment by indrajitdan** [comment]
Also not responsive in IE.

**Comment by nicinabox** [comment]
Firefox 12 is 5 versions old now. Testing that is going to be low on the priority list.

But could you give more info about what IE you saw issues with?

**Comment by iranana** [comment]
It seems to not work for me in Firefox 15.0.1 too. Works fine in Chrome though. Awesome package and wonderfully simple markup, would love to use it in a couple of projects but until browser support becomes a little more stable I don't think my clients would be happy :(

**Comment by nicinabox** [comment]
Ah, I know what this is. There's some odd issue between jQuery 1.8 and jQuery Animate Enhanced <0.99. The issue does not occur with jQuery 1.7. This has been an issue in the past (#7). Updating jQuery Animate Enhanced in the demo seems to fix the issue. 

I did note some downgraded performance in FF 12 with the jQuery Animate Enhanced plugin. Your milage may vary.

If you still see issues with IE, open an issue for those. Thanks for bringing this up!

**Comment by iranana** [comment]
Fantastic, works perfectly thanks! I'll send along a link of it action when I get this project wrapped up

**Comment by nicinabox** [comment]
Awesome, I'd love to see it!
