### ISSUE TITLE
Height Query

### ISSUE THREAD

**Issue by Third-Hyperion** [nicinabox/superslides#222]
Hi,

I have all working as i want etc but i am just wondering is it or could it be possible so that instead it always being 100% height of the window it maybe be like 70% in height?

There is just another instance i would like to use the slider but i would like to see some of the content that follows in the screen also.

Sorry for an awkward question but love the slider and just thought would be nice to use it like this also.

Cheers,

Wes.

**Comment by nicinabox** [comment]
Use the `inherit_height_from` option. Wrap your slider in another element that has a height. See docs for more info.
