### ISSUE TITLE
Problem - how to enable links inside slides

### ISSUE THREAD

**Issue by mabenedek** [nicinabox/superslides#225]
Hi, I succesfully got superslide to work on my website:
http://magdamaciejewska.com/
The full-screen slider is my list view of wordpress posts... I need to enable links to single project, for this purpose I put links to single view inside the slides under the phrase "more". But they do not work, I the page does not change, links are disabled. 

Only the url changes:
http://magdamaciejewska.com/#Magnetism
http://magdamaciejewska.com/magnetism-of-the-heart/#Magnetism

How could I re-activate / enable the links inside slides?

**Comment by mabenedek** [comment]
Sorry, I have resolved my problem. Thanks for great plugin! Very best,

**Comment by phillytep** [comment]
@mabenedek How did you solve this problem?
