### ISSUE TITLE
White screen after animation in Safari

### ISSUE THREAD

**Issue by kr3ved** [nicinabox/superslides#23]
Screen flashes white for a moment after slide animation. Safari 6.0.2 (8536.26.17), MacOS 10.8.2
video: https://www.dropbox.com/s/8sh7aoiyrijl3k6/safari.mov

**Comment by nicinabox** [comment]
I believe this has to do with the backface visibility property. It's so inconsistent across browsers :(

The video is helpful, thank you.

**Comment by nicinabox** [comment]
Good news, this has already been fixed in 0.4.3. It's in the dev branch if you want to grab it from there.

**Comment by kr3ved** [comment]
Awesome! 
Thanks a lot
