### ISSUE TITLE
Mouse actions to change slides

### ISSUE THREAD

**Issue by meugel** [nicinabox/superslides#245]
Hi!

Is there a possibility to use mouse actions (instead of the navigation arrows) to change the slides? Maybe an integration of https://github.com/brandonaaron/jquery-mousewheel or similar? This would be great! 

Thanks
meugel

**Comment by nicinabox** [comment]
Sure, you can use whatever events you want to trigger slide transitions. Read the docs about the API.

**Comment by meugel** [comment]
I am not very familiar with javascript stuff, but I will try …

Thanks again
meugel

**Comment by notcholas** [comment]
Hi
Did you manage to work out a solution to get mousewheel to trigger the slide transitions?
Any help will be greatly appreciated.
Thanks

**Comment by meugel** [comment]
As I mentioned I am not very familiar with javascript stuff, and at the end I used it without mouse wheel trigger.
meugel
