### ISSUE TITLE
How to resize height of the slider

### ISSUE THREAD

**Issue by barbosa-renan** [nicinabox/superslides#250]
I wonder how I can resize the height of the slider, so that the width has maximum size, but the height of the slider has 500 px. 
Thank you.

**Comment by Third-Hyperion** [comment]
wrap a div around id="slider" called eg: id="hero" with css styles of height 500px and width 100%

Then add: 

```
inherit_height_from: '#hero',
inherit_width_from: '#hero'
```

 in your call script eg:

```
<script type="text/javascript">
$('#slides').superslides({
inherit_height_from: '#hero',
inherit_width_from: '#hero'
})
</script>
```
