### ISSUE TITLE
Cropping portrait orientated images

### ISSUE THREAD

**Issue by shogran** [nicinabox/superslides#260]
Hi there,

 Is there a way to prevent superslides from cropping/fitting portrait images to the width of the page and get them to to fit to the height instead? I have a set of photos with both portrait and landscape orientated photos in it and the portrait ones crop out a lot of the image in order to stretch it to the desktop resolution.

If this is not possible can you recommend something that would achieve a similar effect while allowing me to continue using superslides?

Thanks in advance

**Comment by nicinabox** [comment]
Sorry, it's not possible at this time. I suggest editing your images to include the necessary letterboxing.
