### ISSUE TITLE
Callback?

### ISSUE THREAD

**Issue by rowild** [nicinabox/superslides#279]
Are there any callbacks available that fire when an animation has finished?
Also, a pre-animation functionality would probably be great - is there any?

Thank you for your answer!

**Comment by nicinabox** [comment]
Yes, there are pre and post animation events you can listen for. Check the readme for more info.

**Comment by rowild** [comment]
Any chance for a little example? The readme is quite obscure...

**Comment by nicinabox** [comment]
Check the examples directory? 

What's obscure about it? Listen to events on the element. All the events are listed there in the readme.

**Comment by rowild** [comment]
Well, instead of going back and forth in this conversation, a little example would be the quicker solution, maybe for more people than just me... no offense, but the readme is not really giving too much insight on how to use event callbacks for non-programmers. In case you accept this feedback: the readme could be better (at least point to the proper example)

**Comment by nicinabox** [comment]
Unfortunately I'm not near my computer and can't give you an example. This project assumes basic javascript knowledge from the user and is designed as such. The readme is written as a technical document and should be used as a reference.

**Comment by rowild** [comment]
In my opinion a good Readme should contain a little explanation of what something does and a little code sample, not matter whether the piece of software is directed to professionals or beginners. It's a question about quality that OpenSource should adhere to. Especially when it is such a good script as this one!

I don't see any reason why the events section cannot quickly show a line like this:
$('#slides').on('animated.slides', function(){
  // do something
});

It would make everybody's life easier and your software even more popular - because of the "well documented" fact. Instead, I found several similar questions on stackoverflow (it seems I am not the only one asking...) So why not give the answer here right away?

Well, that's my 2 cents, and they are meant as a feedback, not as a critique. If my tone reads different, I'd like to apologize for the wrong choice of words and/or phrases ( I am not an English native speaker).

Anyway, I throw this 2 cents in, because I do not understand the way this script works. When I setup all listeners like this:

``` js
 $('#slides').on('animated.slides', function () {
        console.log("End animation on ", $(this).superslides('current'));
    });

    // before slide animation begins
    $('#slides').on('animating.slides', function () {
        console.log("Begin animation on ", $(this).superslides('current'));
    });

    $('#slides').on('init.slides', function () {
        console.log("Init slides");
    });

    $('#slides').on('started.slides', function () {
        console.log("Started slides");
    });
```

... and reload my site with the fullscreen gallery, the console actually starts with a "animated.slides" and continues with a "init.slides"...? Also the order of the begin and end callbacks are confusing:

``` js
// from the console:
End animation on  0 mySuperSlides.js:31
Init slides mySuperSlides.js:40
Begin animation on  0 mySuperSlides.js:36
End animation on  1 mySuperSlides.js:31
Begin animation on  1 mySuperSlides.js:36
End animation on  2 mySuperSlides.js:31
Begin animation on  2 mySuperSlides.js:36
End animation on  3 
```

I wonder if this is supposed to be like that, but I have the feeling that the callbacks could be splitted up more clearly, something like:
onFocusGain.animationBegin.slides (why is there a slides?)
onFocusGain.animationEnd.slides
onFocusActive.timespanStart.slides
onFocusActive.timespanEnd.slides
onFocusLoose.animationBegin.slides
onFocusLoose.animationEnd.slides

...or something like that. This would enable to control any other things that are going on in the slide, e.g.:
onFocusGain.animationEnd.slides -> start animation of a text that drops in, and optionally only if that animation is finished, continue with onFocusActive.timespanStart

Same thing with an "Outtro":
onFocusActive.timespanEnd.slides -> start the outro animation of any texts in the slide, and only if those are finished, continue with onFocusLoose.animationStart.slides...

I think GSAP by GreenSock could be of help here...

Another idea to improve this already very impressive script would be to present some of those effects that can be added. "sudoSlider" has tons of them, but they are very difficult to extract from there. It would be great, though, to have a little "effects library"...

Thanks for reading!
Have a nice rest-Sunday! :-)

**Comment by nicinabox** [comment]
@rowild I appreciate you taking the time to give feedback. I wasn't trying to sound defensive or mean, just matter-of-fact.

> I don't see any reason why the events section cannot quickly show a line like this

There are in multiple code samples throughout the readme. I'd happily accept a pull request for this change. The only reason it didn't is because it seemed overly verbose. Event listeners like this are an extremely common pattern when using jQuery.

> ... and reload my site with the fullscreen gallery, the console actually starts with a "animated.slides" and continues with a "init.slides"...?

Yes, this is a little confusing. The same code is used to do the initial alignment as is used for all subsequent alignments. I suggest attaching the `animating.slides` event in the `init.slides` callback.
