### ISSUE TITLE
Opera browser issues

### ISSUE THREAD

**Issue by randalldon** [nicinabox/superslides#31]
Hi There,

I have noticed that the demo (http://nicinabox.github.com/superslides/) doesn't function at all in the Opera browser. I get the previous & next buttons but just a white screen with the images or content not showing. Is there any way to fix this?

Regards

Brendan Randall

**Comment by nicinabox** [comment]
To be honest, no testing has been done in Opera. It hasn't been a priority since their browser share is just over 1% worldwide. Maybe we can change that in 0.5

**Comment by nicinabox** [comment]
Just checked 0.5.0-wip in Opera. Working great with the exception of some minor performance issues :)

http://i.imgur.com/5l0c0.jpg

**Comment by randalldon** [comment]
This is great news. Performance issues aside as long as superslides is functional in Opera i.e. content can be viewed then superb. Is there a timeline for 0.5.0 release? I can use the extra slide hack to get around the single slide aspect for now but the Opera fix is key for a live project.

Many thanks.

**Comment by nicinabox** [comment]
I'm shooting to release this weekend. Hopefully no later than Monday. I think it should be stable enough for testing if you want to try it out (0.5-wip branch). Be sure to read over the new docs, some things have changed.
