### ISSUE TITLE
Best way to implement as CommonJS module?

### ISSUE THREAD

**Issue by Gaffen** [nicinabox/superslides#314]
I've just started using this library (which looks like a very nice solution indeed so far!), but ran into a small road block when I was starting with it:

```
(function(window, $) {
    ...
})(this, jQuery);
```

When using something like

```
 require('superslides');
```

`this !== window`, leading to an error on invocation of the library. Would there be a recommended way around this? at the moment I have taken to modifying the code and removing the 'this' argument, but that obviously isn't the best solution.

**Comment by nicinabox** [comment]
This would be awesome. Unfortunately superslides was written long before I knew about CommonJS modules and has basically no support for it. Your best bet is to modify it to work for you.

**Comment by Gaffen** [comment]
No worries, thanks for such a quick response!

Is there a reason for passing `window` to the self invoking function? Removing it seems to solve this issue. Alternately `this` could be changed to `window` in outro.js.

**Comment by nicinabox** [comment]
I think that's an old jquery thing.

**Comment by Gaffen** [comment]
Ah, I see. Thanks again!
