### ISSUE TITLE
min/max-width in ie

### ISSUE THREAD

**Issue by randalldon** [nicinabox/superslides#32]
As you mentioned in the front page notes i see that ie7 & ie8 stop scaling the background image beyond a certain point when reducing the size of the browser window. You mentioned that you can remedy this with a polyfill. Do you know the polyfill or where this could be sourced from?

Many thanks in advance.

**Comment by nicinabox** [comment]
This may have been an issue at one point, but I don't think it is anymore. IE7+ behaves consistent with other browsers  now.
