### ISSUE TITLE
First slide is visible after animation

### ISSUE THREAD

**Issue by Gramatton** [nicinabox/superslides#34]
Hi. After update to 0.5, the first slide is always visible. So if you have semi-transparent backgrounds (or just content w/o background image) you'll see the first slide content.

P.S. there was no such problem in 0.4.3

**Comment by nicinabox** [comment]
Ahhh, Thanks. I see that; definitely a bug.

**Comment by nicinabox** [comment]
Fixed in 0.5-stable branch.
