### ISSUE TITLE
Is there any way to set a custom duration for each item?

### ISSUE THREAD

**Issue by fpena** [nicinabox/superslides#354]
For example, override the default play duration for each element with a property within the element:

<li ... duration="5000"> 
... content ...
</li>

or 

<img ... duration="5000" ... />

**Comment by nicinabox** [comment]
Sorry, this is not possible with the current configuration. One duration applies to all slides.

**Comment by fpena** [comment]
OK, thanks.

————
Felipe Peña Riveros
http://felipe.penya.cl

El 26 de mayo de 2016 a las 10:21:06 a.m., Nic Aitch (
notifications@github.com) escribió:

Sorry, this is not possible with the current configuration. One duration
applies to all slides.
