### ISSUE TITLE
Last slide disappears after reload

### ISSUE THREAD

**Issue by pmaly** [nicinabox/superslides#38]
Hi!

If I'm on the last slide and hit reload, the content disappears. Then if I browser to another slide and come back, the contant reappears.

http://egelect.com/2013/superslides.html

Thanks for the help.

**Comment by nicinabox** [comment]
Try grabbing the 0.5.1 release. I'm not seeing the behavior in the demo, so that might fix it for you.

**Comment by pmaly** [comment]
That's the version I have installed... Just checked the demo and I get the same behavior (local and remote : http://egelect.com/2013/superslides/demo/index.html). I get the same behavior on http://nicinabox.github.com/superslides

Tested on Chrome (23.0.1271.97 m), Firefox (17.0.1) and IE (9.9.8112.16421)

Thanks.

**Comment by nicinabox** [comment]
Ahh, I see this in the demo now. Can't go directly to the last slide for some reason.

**Comment by nicinabox** [comment]
Fixed in 0.5.2 to be released today.
