### ISSUE TITLE
Opera browser issues still with v0.5.1

### ISSUE THREAD

**Issue by randalldon** [nicinabox/superslides#39]
Hi There,

I've been having a look through v0.5.1 and it looks great. However, i know you mentioned that v5 was was working in Opera when i raised the issue for v4 but i can't seem to get this to function. Even the demo doesn't function in Opera - it just presents a white screen, with arrow but no images. Details of my Opera set-up are below:

Version: 12.50 internal 
Build: 1497 
Platform: Win32 
System: Windows 7

Cheers

**Comment by randalldon** [comment]
Hi There,

Just as an update to this when inspecting the generated html i notice that with all other browsers the <ul> with the class .slides-container has a display value of 'block' set within the generated style on this element. However, the same <ul> element when inspected in Opera it has a display property of 'none' set within the generated style on this element.

If i use a little jquery to change this property when the document is ready:

$(document).ready(function() {
    $('.slides-container').css({'display':'block'});  
});

This actually makes the slide visible but has the side-effect of it sliding in from the left when first loaded and this initial slide-in behaviour is subsequently inherited in other browsers. The navigation subsequently appears broken In Opera as the navigation links don't have numeric references i.e. the arrows just have # rather than #1 etc so i presume this is why the slides can't be navigated.

Hopefully this investigation in Opera can help in some fashion to diagnose these issues for this browser.

Many thanks.

**Comment by randalldon** [comment]
An additional update to this issue is that it seems superslides v0.5.1 works in Opera 11 as i donwloaded thsi legacy browser to test. Well, when i say works you don't get the sliding animation when navigation between slides but the content is visible and the slides navigation functions. It seems the issue lies with Opera 12.

Hope this helps.

Many thanks.

**Comment by randalldon** [comment]
Is there any update to this? It's a bit of a killer at the moment.

**Comment by nicinabox** [comment]
Unfortunately my production schedule has been too tight recently to address some of these issues. I'm hoping to get back at it this week.

But about Opera...it does work in Opera 12.12 on OSX (http://min.us/lTG7IpeZfjbgH). I wonder what's different about the Windows version.

**Comment by nicinabox** [comment]
Just tested on Opera 12.12 on Windows 7 (http://minus.com/lbsZfcUidfFGPr) and it seems to work fine there as well.

What is "12.50 internal"?

**Comment by randalldon** [comment]
Thanks for having a look. I'm starting to think there may be an issue with my Opera installation. I'm working on Windows 7 too and Opera confirms i'm on the latest version and so now update is available. When accessing About Opera in the current set-up the details are as below:

About Opera
Version information
Version
12.50 internal 
Build
1497 
Platform
Win32 
System
Windows 7 
XHTML+Voice
Plug-in not loaded 
Browser identification

Opera/9.80 (Windows NT 6.1; WOW64; U; Edition Next; en) Presto/2.11.310 Version/12.50

I'm not really sure what the internal is either.

I'll mark this as closed for now pending some further investigation from my end.

Cheers

**Comment by nicinabox** [comment]
Feel free to reopen (or I can) if there is an issue :)
