### ISSUE TITLE
keep-original class appears to be broken in 0.5

### ISSUE THREAD

**Issue by randalldon** [nicinabox/superslides#40]
Hi There,

Having been looking into version 0.5 it seems the .keep-original class for preserving additional images appear to no longer work. Can you confirm this bug?

Cheers

**Comment by randalldon** [comment]
Update to this. I see now that the class is .preserve rather than .keep-original in 0.5. This stops the additional image being resized from the original but it is still pulled out of the dom and placed alongside the main background image even with the .preserve class added.

So, i amended line 111 of jquery.superslides.js from:

return $(this).find('img:first-child').insertBefore($('.scrollable', this));

to

return $(this).find('img').not('.preserve').insertBefore($('.scrollable', this));

Which prevents this behaviour and the image is now preserved.

Hope this helps.

Cheers

**Comment by nicinabox** [comment]
Yes, that should definitely be using the class instead of `first-child`. Good catch.

**Comment by hejamartin** [comment]
Thanks Randalldon. 

Could you commit this change as well nicinabox?

**Comment by nicinabox** [comment]
Fixed in the next release (0.5.2)
