### ISSUE TITLE
min-width site issue when using superslides

### ISSUE THREAD

**Issue by randalldon** [nicinabox/superslides#41]
Hi there,

I need to set a minimum width for my website. i.e. 960px but superslides seems to prevent this behaviour. The min-width should present a horizontal scrollbar once the viewport is less that 960px but when using superslides the horizontal scrollbar is never shown and content becomes clipped without the ability to scroll. Is there a method for setting a minimum width with superslides that will not break this behaviour?

Many thanks in advance.

**Comment by nicinabox** [comment]
Hm, it's designed to be fullscreen, edge to edge. Currently, just attaching it to a block element with it's own width constraint is not supported.

**Comment by randalldon** [comment]
Hi There,

I appreciate the superslides aspect is intended to be fullscreen and edge to edge but consider the use case where at a certain resolution the content within the slide has a minimum width. Currently superslides prevents the minimum width of the slide content being respected and as such beyond that minimum width the actual slide content gets clipped on the right edge making it partially invisible. It's not really a case of placing superslides in a block element but more a case of allowing it to respect the inner content's minimum width.

Cheers
