### ISSUE TITLE
0.5 Getting current slide & number of slides

### ISSUE THREAD

**Issue by randalldon** [nicinabox/superslides#44]
Hi there,

I need to be able to log the current slide ref and also be able to get the total number of slides. I had this working in the previous version but this logic now seems out of date with 0.5. Could you advise how i can acheive this with 0.5.

Many thanks in advance.

**Comment by randalldon** [comment]
No need to worry about this. I can see now that:

$('#slides').superslides('current') = current slide
$('#slides').superslides('size') = number of slides.

Many thanks

**Comment by nicinabox** [comment]
Glad you got it. I'd like to setup a proper, formatted documentation page soon. It's definitely lacking a bit.
