### ISSUE TITLE
Stopping autoplay on last slide

### ISSUE THREAD

**Issue by cybersb** [nicinabox/superslides#45]
Hey, is it possible to stop autoplay when the last slide is displayed, so it will just stay on without going back to the first slide again? Thanks!

**Comment by nicinabox** [comment]
Sure! You'd need to write your own code for this, but it's very possible through the [API](https://github.com/nicinabox/superslides#api). The basic process would be:
- Listen for the `animated.slides` event
- Check if the current slide is equal to the size
- Call stop
