### ISSUE TITLE
Fade in latest version

### ISSUE THREAD

**Issue by VladNov** [nicinabox/superslides#46]
Hi Nic, have you added the fade effect in the latest version? Thanks.

**Comment by nicinabox** [comment]
Not yet! Aside from bugfixes, it's the next major feature on the list.

**Comment by pmccauley** [comment]
would this be something easy to "hack in" - I was trying to see if I could figure this out. Great slider by the way:)

**Comment by nicinabox** [comment]
Thanks!

It just needs a little setup first. I have an idea of how I want to do it, just need to put down some groundwork so animations can be extended easily.

**Comment by christian70** [comment]
This jQuery plugin is amazing. Especially for the well-written code, that shows images list very clearly and seo customizable. In my opinion the fadein effect is the only extra-feature that should be included. I tried to figure it out but I didn't (not very good at jQuery). I do hope somebody could make it successfully. Thanx for sharing it anyway.

**Comment by nicinabox** [comment]
Thanks for the compliments @christian70. Rebuilding the animation aspect is one of my top priorities for this project. I just need to find a weekend to do it :/

**Comment by ironchef1369** [comment]
Any update on the availability of the fade?  Thanks!

**Comment by nicinabox** [comment]
I have an update!

I am edging ever closer to releasing 0.6.0 with slide and fade as well as the ability to add custom animations. It's going to be on a production site next week, so keep a look out shortly after that. Check out the master branch demos for an peek.

**Comment by matthewcarleton** [comment]
Is Superslides any closer to a fade feature? I would love to add this to my project!!

**Comment by nicinabox** [comment]
@matthewcarleton Fade is working, but I need to bring a few other features back in. Check master branch examples for features you might want.

**Comment by fabyeah** [comment]
thx for fade! demo is looking great!
multiples demo not working yet? 
Requesting multiples :)
Awesome plugin!

**Comment by nicinabox** [comment]
Grab 0.6.0 beta from master if you want to use fade. I'm using it in a couple production sites currently.
