### ISSUE TITLE
Resizing the window removes scroll bars to content below slider

### ISSUE THREAD

**Issue by schaafm** [nicinabox/superslides#48]
See http://mobius.com.au/responsive/

Current behaviour - When you resize the window, superslides prevents scrolling down to see the rest of the content. 

Expected behaviour - Able to scroll as when the page loads.

**Comment by nicinabox** [comment]
Just pushed a fix to 0.5-stable branch. See if that works for you. 

Good looking site, btw :)

**Comment by schaafm** [comment]
That seems to have fixed it, many thanks for the great slider!

**Comment by jakubbaranski** [comment]
Hello! I'm testing superslides ( really good job! :) ) and I'm still having the problem described by @ginji: when I resize the window - the scroll disappears and it's not possible to scroll down ( please see: http://jakubbaranski.home.pl/inteoria_dev1/ ). Am I doing something wrong?

**Comment by nicinabox** [comment]
@jakubbaranski grab the code from the 0.5-stable branch. It has the fix you're looking for.

**Comment by jakubbaranski** [comment]
Thanks for this rapid help. :) I thought I have downloaded 0.5-stable branch before, but I didn't.

**Comment by oohtruck** [comment]
this is happening to me as well, i'm using v0.5.2, any ideas?
