### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by ghost** [nicinabox/superslides#49]
I added Vimeo video to the slider. ( 1 minut long ) and I have problem.

Video have autoplay. But when I change slide to another the video do not stop and play on.

So, when I am on another slide, only with image  I hear music from the video. 

The FlexSlider (http://flexslider.woothemes.com/video.html) have API which is working like I would like. Any ideas?

**Comment by nicinabox** [comment]
Use the `animated.slides` event to play/pause the video (using Vimeo's API)

**Comment by ghost** [comment]
Im not sure what to do.

I know that I must use foogaloop.js, but what exactly I should add to my superslide ?

<pre>$(window).load(function(){
        $('#slides').superslides({
            play: false,
            slide_easing: 'easeInOutCubic',
            slide_speed: 800,
            animatedslides: true,
            delay: 6500,
            pagination: true
        });
        $('#slides').on('dragstart', function (event) {
            event.preventDefault();
            switch(event.direction){
                case "left":
                    $('#slides').superslides.api.next();
                    break;
                case "right":
                    $('#slides').superslides.api.prev();
                    break;
            };
        });
    });</pre>

**Comment by nicinabox** [comment]
Probably something along these lines.

``` javascript
$(window).load(function(){
  var $slides = $('#slides');

  // Vimeo API
  var player = document.getElementById('player_1');
  $f(player).addEvent('ready', ready);

  function addEvent(element, eventName, callback) {
    if (element.addEventListener) {
      element.addEventListener(eventName, callback, false)
    } else {
      element.attachEvent(eventName, callback, false);
    }
  }

  function ready(player_id) {
    var froogaloop = $f(player_id);
    froogaloop.addEvent('play', function(data) {
      $slides.superslides('stop');
    });
    froogaloop.addEvent('pause', function(data) {
      $slides.superslides('start');
    });
  }

  // Pause video when slides animate
  $slides.on('animated.slides', function() {
    $f(player).api('pause');
  })

  // Initialize slider
  $slides.superslides();

});
```

**Comment by ghost** [comment]
Thanks, but video don't stop when I click to next slide

**Comment by nicinabox** [comment]
I'm not familiar with froogaloop or the Vimeo API. Above is basically the code from flexslider with the superslides api swapped out.

**Comment by mikejandreau** [comment]
I'm having a similar issue with using YouTube videos with superslides - they remain playing when I move to another slide.  What would I have to add to make the YouTube video stop/pause when going to another slide?

Thanks in advance!
