### ISSUE TITLE
trying to write a custom function using superslides event

### ISSUE THREAD

**Issue by dandanv** [nicinabox/superslides#51]
im trying to write a simple custom function using superslides event. javascript isn't my strong suite. I do understand the logic though. basically i just want to write something as simple as
if current slide = whatever then do something. problem is that when i use the API 'current' it always equals to -1.  also i'm not sure how to use the event handlers. was hoping you can provide some sort of example.

cheers,
Dan

**Comment by randalldon** [comment]
Hey dandanv,

I've worked with just this logic so i thought i'd help you out here. I think it depends which version of superlisdes you're using but if you're using the latest version i.e. v0.5.2 the logic is as below:

``` javascript
// Get total number of slides
numberofslides = $('#slides').superslides('size');
// Get current slide
currentslide = $('#slides').superslides('current');

if (currentslide === 0) { // first slide
// do logic here if required
} 
if (currentslide === numberofslides-1) { // last slide
// do logic here if required
}
```

Hope it helps

Cheers

**Comment by randalldon** [comment]
And on your second query regarding usage of event handlers if you're using jquery a usage would be:

``` javascript
$(document).on('animated.slides', function() {
// do logic here
});
```

Other events handlers are:

```
started.slides
init.slides
animated.slides
updated.slides
```

Again, hope this helps.

Cheers

**Comment by dandanv** [comment]
Hi Randalldon, thank you so much. i learned alot from this.

**Comment by eriksjaastad** [comment]
Would curIndex work for this as well? My first nav goes to a new page but the Superslides is behind the home page http://themartin.logicdesigns.com/demo/
