### ISSUE TITLE
Problem setting .active in outer menu

### ISSUE THREAD

**Issue by ezemosho** [nicinabox/superslides#53]
Here´s my issue:

I´ve got 15 slides but 6 sections. 

Section A = Slide 1
Section B = Slide 2
Section C = Slide 3 and Slide 4
Section D = Slide 5 to Slide 13
Section E = Slide 14
Section F = Slide 15

Default pagination <a> tags work excellent for navigation slide by slide.
Linking by href="#0" to specific slides works great too.

Now I need to add .active class to my sections menu while showing .current class for nav.slides-pagination without making a mess. It seems easy but every attempt I tried so far, crashed everything :S Is it possible?

The menu look like this:

<div id="menu">
<a href="#0" class="active">Section A</a>
<a href="#1">Section B</a>
<a href="#2">Section C</a>
<a href="#4">Section D</a>
<a href="#13">Section E</a>
<a href="#14">Section F</a>
</div>

Here´s a link to the work-in-progress website:

www.estudiocalendar.com/clients/lowcost2

Thanks in advance! Everyone here it´s always smarter than me YuY

**Comment by ezemosho** [comment]
I´ve solved the problem but not so well. I added this lines inside the plugin at line 336

if (_this.options.hashchange) {
          window.location.hash = _this.current;

```
    $("#menu a").removeClass("active");

    if("#0" == window.location.hash) { $("#menu a.home").addClass("active") }
    if("#1" == window.location.hash) { $("#menu a.que-es").addClass("active") }
    if("#2" == window.location.hash) { $("#menu a.pasos-a-seguir").addClass("active")}
    if("#3" == window.location.hash) { $("#menu a.pasos-a-seguir").addClass("active")}
    if("#4" == window.location.hash) { $("#menu a.modelo-de-casa").addClass("active")}
    if("#5" == window.location.hash) { $("#menu a.modelo-de-casa").addClass("active")}
    if("#6" == window.location.hash) { $("#menu a.modelo-de-casa").addClass("active")}
    if("#7" == window.location.hash) { $("#menu a.modelo-de-casa").addClass("active")}
    if("#8" == window.location.hash) { $("#menu a.modelo-de-casa").addClass("active")}
    if("#9" == window.location.hash) { $("#menu a.modelo-de-casa").addClass("active")}
    if("#10" == window.location.hash) { $("#menu a.modelo-de-casa").addClass("active")}
    if("#11" == window.location.hash) { $("#menu a.modelo-de-casa").addClass("active")}
    if("#12" == window.location.hash) { $("#menu a.modelo-de-casa").addClass("active")}
    if("#13" == window.location.hash) { $("#menu a.faq").addClass("active") }
    if("#14" == window.location.hash) { $("#menu a.contacto").addClass("active") }
    }
```

I know that it´s not the best solution but it works!

**Comment by nicinabox** [comment]
This is not an issue with Superslides.

I'd recommend listening for the hashchange event and setting your navigation active state that way.

**Comment by ezemosho** [comment]
Thank you and sorry my newbieness ;)
