### ISSUE TITLE
Adding Overlay

### ISSUE THREAD

**Issue by marcopixel** [nicinabox/superslides#54]
Hey,

could you add an option where you can easily add an overlay (from PNG) to the images without overlaying the text?

Currently its only working propertly if you add the background to "#slides .scrollable".

Greets,
Marco

**Comment by nicinabox** [comment]
Not likely, but please provide a use case.

**Comment by marcopixel** [comment]
Okay, my fault. 
It looked like it was overwriting it but it isnt. Its working now propertly.

Greets,
Marco

**Comment by greetp** [comment]
@MarcoPixel , could you post your solution? I'm trying hard but cannot make the overlay work.
Thanks,
Greet

**Comment by Prokophs** [comment]
Here is how I do it but with css.

<div id="slides">
                <ul class="slides-container">
                    
                    <li>
                        <div class="gradient-overlay gradient-4 opacity-60"></div>

```
                    <img src="img/media/home/3.jpg" alt="" data-stellar-ratio="0.4">
                    <div class="caption-wrapper roll-in white-text">
                        <div class="slide-caption">
                            <span class="little-line"></span>
                            <a href="#">
                                <h1 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.6s">Experience The blue Ionian feeling</h1>
                            </a>

                            <h6 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.6s">Sed dolor mi, volutpat quis tristique sit amet, varius quis justo.</h6>
                        </div>
                    </div>
                </li>
                <!-- end slide item -->
                <!-- slide item -->
                <li>
                    <div class="gradient-overlay gradient-4 opacity-60"></div>
                    <img src="img/media/home/home2.jpg" alt="" data-stellar-ratio="0.4">
                    <div class="caption-wrapper white-text">
                        <div class="slide-caption">
                            <a href="#">
                                <h1 class="wow fadeInDown" data-wow-duration="1s" data-wow-delay="0.6s">Fashion Illustration</h1>
                            </a>
                            <h6 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.6s">Sed dolor mi, volutpat quis tristique sit amet, varius quis justo.</h6>
                        </div>
                    </div>
                </li>
                <!-- end slide item -->
            </ul>
            <!-- slide navigation -->
            <nav class="slides-navigation">
                <a href="#" class="prev">Prev</a>
                <a href="#" class="next">Next</a>
            </nav>
        </div>
      <!-- end #slides -->
```

The css for overlay:

.gradient-overlay {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 0;
}
.gradient-0 {
    background: rgb(125,167,243); /\* Old browsers _/
    /_ IE9 SVG, needs conditional override of 'filter' to 'none' _/
    background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzdkYTdmMyIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjUwJSIgc3RvcC1jb2xvcj0iIzRkYjJjNSIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiM0MmVlZTciIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
    background: -moz-linear-gradient(top,  rgba(125,167,243,1) 0%, rgba(77,178,197,1) 50%, rgba(66,238,231,1) 100%); /_ FF3.6+ _/
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(125,167,243,1)), color-stop(50%,rgba(77,178,197,1)), color-stop(100%,rgba(66,238,231,1))); /_ Chrome,Safari4+ _/
    background: -webkit-linear-gradient(top,  rgba(125,167,243,1) 0%,rgba(77,178,197,1) 50%,rgba(66,238,231,1) 100%); /_ Chrome10+,Safari5.1+ _/
    background: -o-linear-gradient(top,  rgba(125,167,243,1) 0%,rgba(77,178,197,1) 50%,rgba(66,238,231,1) 100%); /_ Opera 11.10+ _/
    background: -ms-linear-gradient(top,  rgba(125,167,243,1) 0%,rgba(77,178,197,1) 50%,rgba(66,238,231,1) 100%); /_ IE10+ _/
    background: linear-gradient(to bottom,  rgba(125,167,243,1) 0%,rgba(77,178,197,1) 50%,rgba(66,238,231,1) 100%); /_ W3C _/
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#7da7f3', endColorstr='#42eee7',GradientType=0 ); /_ IE6-8 */
}

.opacity-60 {
    opacity: 0.60;
}

---

Hope it helps
