### ISSUE TITLE
IE navigation and Pagination problem

### ISSUE THREAD

**Issue by artavenir** [nicinabox/superslides#58]
Hi! 

I have used your slider on our development site and so far it works great on the other browsers except for the IE8. 

I can't seem to bring up the arrow buttons for navigating through the slide left and right. 

Also, just like in the demo the pagination doesn't seem to work when you click on it, it doesn't take you to another slide. I just don't know what else I could do with it, I appreciate your help on this. Thank you in advance. :)

**Comment by nicinabox** [comment]
I have noticed this as well. I'm porting to JavaScript from Coffeescript and plan on addressing it during that. Any help is super appreciated though. I'd definitely merge a pull request that fixes the issue :)

**Comment by artavenir** [comment]
Thank you! Cheers!

**Comment by jrtmns** [comment]
Has this issue been addressed yet? Grabbed the library last week and everything is working perfectly except for not being able to click the pagination links in IE7.

**Comment by frodoschering** [comment]
I am having similar issues. Everything works fine in all browsers except IE7 and IE8. In those browsers the next and previous links don't show up. Is there a fix for this?

Oh, and thanks for a great plugin!

**Comment by nicinabox** [comment]
@frodoschering What version are you using?

**Comment by frodoschering** [comment]
I was using version 0.5.2 but upgraded to 0.6.1 this afternoon. Copied over the javascript files that is.

**Comment by nicinabox** [comment]
What's the css for your navigation?

0.6.1 should definitely work. 
![screen shot 2013-07-10 at 12 06 37 pm](https://f.cloud.github.com/assets/246280/776286/21c0381c-e983-11e2-9c36-828a6464a5b9.png)

**Comment by frodoschering** [comment]
Ok, so I downloaded 0.6.2 and ran that from my server just to be sure it is not something I did that is interfering. The examples show no previous/next links on both ie7 and 8. When I view http://nicinabox.github.io/superslides it does display correctly in IE8. In IE7 the arrows don't show(the border does) and the pagination links are left aligned.

So it looks like your website has some extra css added which makes the links show up?

**Comment by frodoschering** [comment]
I think I found the problem! I have the scripts loading at the bottom of the page. When I move them to the top of the page the navigation links show up in both IE7 and IE8. The examples also have the script at the bottom and your site has them at the top so that would explain why they display differently.

**Comment by nicinabox** [comment]
How interesting. I would not expect that to have any impact on their display.

**Comment by frodoschering** [comment]
Internet Explorer works in mysterious ways..
