### ISSUE TITLE
tabbed or browsing through the slides

### ISSUE THREAD

**Issue by iveenano** [nicinabox/superslides#6]
HI,

Great slider ..!

i was just wondering how to add a navigation menu or tabs to browse through the slides and provide a url for each one of them  that can de triggered at pageload.

something like 
example.com/#1
example.com/#2 
...

var startSlide = 0 

   if (location.hash == "#1") { 
                startSlide = 1; 
                } 
        if (location.hash == "#2") { 
                startSlide = 2; 
        } 
        if (location.hash == "#3") { 
                startSlide = 3; 
        } 
        if (location.hash == "#4") { 
                startSlide = 4; 
        } 
        if (location.hash == "#5") { 
                startSlide = 5; 
        } 
        if (location.hash == "#6") { 
                startSlide = 6; 
        } 
        if (location.hash == "#7") { 
                startSlide = 7; 

```
    }
```

Thanks

**Comment by nicinabox** [comment]
Pagination is a feature I started on, but never finished. I'll try adding this before the end of the week.

**Comment by vachi** [comment]
hey hey, any change on this?
i have been trying to integrate it with no success, have the same problem as @iveenano
would be super awesome to have something working of the sort

**Comment by nicinabox** [comment]
No changes yet. Been wrapping up other projects to swing around to this. I haven't forgotten about it :)

**Comment by vachi** [comment]
cool :), 
question, i have two links/tabs/#/hashes/clicks, i am trying to make it so when clicked the slider would go to first slide and the other to the last slide
any ideas?

**Comment by nicinabox** [comment]
I now remember why I stalled on this originally. This requires exposing a public api that can be used like `$el.superslides('animate', 'next')`. That, in turn, requires reworking the quite a bit to create this sort of api. I'm in process on it and shooting for and update late weekend.

**Comment by vachi** [comment]
yeah i been trying to modify your code today, added vertical ratio check
and started working on the tabs but stopped when i realized the same thing as you :)
you can see the vertical img check in action on this page
http://balmori-production.herokuapp.com/portfolio/campa-de-los-ingleses-park

**Comment by nicinabox** [comment]
If you're really itching to test it out, there's some new code on the dev branch that includes api methods.

Available methods are:
- start
- stop
- play
- animate
- next
- prev

Example usage:

```
$el.superslides('animate', 'next')
$el.superslides('animate', 3)
$el.superslides('stop')
...
```

More documentation when more is fleshed out.

**Comment by nicinabox** [comment]
0.4 is released with support for pagination and hashchange. Check the updated documentation for more info. Enjoy!

**Comment by vachi** [comment]
Awesome!!

**Comment by iveenano** [comment]
Great dude..cheers !!!
