### ISSUE TITLE
Stop playing when arrows are clicked

### ISSUE THREAD

**Issue by christian70** [nicinabox/superslides#62]
Hello. As I said previously this plugin looks and works like a charm. Waiting intensely for the fade effect to be implemented, I've noticed this: I set the play option to time delay (true) but when you click on arrows to move forward or backward the automatic playing stops and you must go on clicking next or prev to browse sliders. Is there any possibility to avoid it? I'd like to keep slider moves on automatically according to delay time fixed even after click event... Thanx a lot, anyway.

**Comment by nicinabox** [comment]
I think I can make this happen.

**Comment by AntonBoshoff** [comment]
Hi nicinabox. Great plugin! Would love for you to look at this, I have added some caption animations but because of this issue it doesn't work properly. I have tried re-initiating the slider after a click event but to no success. Your help will be greatly appreciated!

**Comment by nicinabox** [comment]
Hey, you're in luck! 0.6.0-beta2 already works this way. Check out the [Play](https://github.com/nicinabox/superslides/blob/master/examples/play.html) example on master.

**Comment by AntonBoshoff** [comment]
Hi nicinabox, I have tripple checked to make sure it is not my mistake but it doesn't continue playing after clicking prev/next. I am not looking to pause the slider on mouseenter. Just looking to have the prev/next not stopping the <code>play: 5000</code> loop. Thanks again for your help!

**Comment by nicinabox** [comment]
Ahh my mistake. That was a false positive. Look for 6.0.1 today.

**Comment by nicinabox** [comment]
0.6.1 is out with this fix.

**Comment by AntonBoshoff** [comment]
Brilliant!! Thanks so much!
