### ISSUE TITLE
Custom hash links for pagination

### ISSUE THREAD

**Issue by hereswhatidid** [nicinabox/superslides#63]
Is it possible to use custom hash links for the pagination navigation?  For example, rather than #0, #1, #2 it could be #dog, #cat, #bird which would then slide to the corresponding image?

**Comment by trialanderrorman** [comment]
That would be amazing... looking forward for an answer!

**Comment by nicinabox** [comment]
I imagine this could easily be added through a data-hash attribute or something.

**Comment by jongacnik** [comment]
Hey all, 

I've added this functionality here: https://github.com/amongiants/superslides/tree/text-hash
And a demo: http://jongacnik.com/dev/superslides/demo/

**Comment by nicinabox** [comment]
Added to 0.6.0.

**Comment by jongacnik** [comment]
@nicinabox great! Sorry I disappeared on this one, been out of country traveling. Hopefully my additions were helpful in integrating. Congrats!
