### ISSUE TITLE
Load Slides via AJAX

### ISSUE THREAD

**Issue by brendenpalmer** [nicinabox/superslides#66]
I know that you had mentioned somewhere that support for AJAX loaded slides was added, but I cannot figure out how to get it to work.

What I am doing is loading the data in via a Jquery AJAX GET request, but I can't get these slides loaded into the slider properly. The data that's being loaded via AJAX is being parsed as a string, essentially something similar to the following:

``` html
li
  img src='' alt='' 
  div class='container' /div
/li
```

What I want to be able to do is append this slide, or slide(s) onto the already initialized slider.

Any ideas?

Thanks in advance

**Comment by nicinabox** [comment]
Use jQuery to append the html inside the container then run the `.superslides('update')` method to let Superslides know the size has changed. That should work just fine.

**Comment by brendenpalmer** [comment]
I do that, and call update, the size changes just fine, but the pictures are not loaded in? I've attached an image as to what it looks like.
![Screen Shot 2013-04-02 at 3 25 37 PM](https://f.cloud.github.com/assets/2276050/330370/31628438-9bcb-11e2-862f-8eab9be09b5b.JPG)

**Comment by nicinabox** [comment]
Hmm, can you post an actual sample of the html you're adding?

**Comment by brendenpalmer** [comment]
Sure - if you go to http://picspace.me, and click on one of the images on the right side, then the slideshow will start. If you inspect the element in Chrome, Firefox, or Safari, you could see the exact HTML.

**Comment by nicinabox** [comment]
Blerg, I see it. I think it should be calling `adjustSlidesSize`, on update, but alas, it isn't :(

**Comment by brendenpalmer** [comment]
Anything I can do to fix it?

**Comment by nicinabox** [comment]
Sure, if you're just wanting to make your local copy work, try adding to the `this.update` method at the beginning:

``` javascript
adjustSlidesSize(this.$el);
```

**Comment by brendenpalmer** [comment]
Sorry, where exactly do I add that line of code? Can't seem to get it working.

**Comment by nicinabox** [comment]
Right after this line: https://github.com/nicinabox/superslides/blob/0.5-stable/dist/jquery.superslides.js#L364

I'm mostly speculating here. I haven't tested it, but I think that should work. The problem is that it's not recalculating the new slide positions.

**Comment by brendenpalmer** [comment]
Didn't work. I see another problem here too. If I click the Load More button on that site (in my case), it's trying to append 12 slides, but there are only 12 buttons when there should be 18.

**Comment by nicinabox** [comment]
Yeah I see that. Some issues here ;(

**Comment by brendenpalmer** [comment]
Any ideas or thoughts on what could be done :) ?

**Comment by nicinabox** [comment]
Oops, try this instead (same line): `adjustSlidesSize($children);`

**Comment by brendenpalmer** [comment]
Nope, didn't work :(

**Comment by nicinabox** [comment]
I need to sit down with it then. I'll try to get it corrected this evening. Sorry man.

**Comment by brendenpalmer** [comment]
No problem at all. Great plugin btw.

**Comment by nicinabox** [comment]
@shootingrubber Grab the code from the 0.5-stable branch now. It should fix this issue.

**Comment by brendenpalmer** [comment]
It fixes it and loads all of the images fine now, but the animation is not normal like when the plugin is first initialized.

To repeat the problem, got to http://picspace.me. Click on any image and the slider will work as normal. Then, exit the slider, press load more, and try using the slider after the 6th picture. The picture will eventually come up, but it does not slide like the originally loaded images.

**Comment by brendenpalmer** [comment]
Actually I think this may be because the images are not loaded, I am not sure. I will do some further testing.

**Comment by nicinabox** [comment]
I see it happening. The images appear to be loaded.

**Comment by brendenpalmer** [comment]
Nevermind, the images are loaded, but it still occurs.

**Comment by nicinabox** [comment]
Try from 0.5-stable again. I think the images just needed CSS.

**Comment by brendenpalmer** [comment]
It appears to be working now! Thanks so much. I'll post here again if there's anything that doesn't appear to be working, but so far, so good.

Thanks so much

**Comment by nicinabox** [comment]
Superb!
