### ISSUE TITLE
Zoomed in ratio

### ISSUE THREAD

**Issue by sharpmachine** [nicinabox/superslides#68]
Hi.  How do I change how much the image actually zooms in.

The first pic is what I'm developing, while the 2nd is what it's suppose to be.  Notice the 2nd has much for space above her head, etc?  So do I change the amount that the plugin zooms in?

![Screen Shot 2013-04-10 at 5 00 17 PM](https://f.cloud.github.com/assets/600836/365234/14efb534-a23b-11e2-819b-8741863d25f6.png)
![Screen Shot 2013-04-10 at 5 00 59 PM](https://f.cloud.github.com/assets/600836/365237/1fbb4514-a23b-11e2-8589-91765c767b1d.png)

**Comment by sharpmachine** [comment]
HELP!!! PLEASE!!!

**Comment by nicinabox** [comment]
You'll need to size the image accordingly. The window size changes how the image is positioned and zoomed. I would recommend not trying to position to an exact pixel area, but rather allow flexibility in your design. Your users will not be using an ideal window size most likely.
