### ISSUE TITLE
Touch slide

### ISSUE THREAD

**Issue by iveenano** [nicinabox/superslides#7]
A small contribution with a touch or swipe enabled superslide with jquery.touchwipe.1.1.1.js !

Tested on Ipad 2 . Works like a charm. Hope to see something similar included in your next version

 <script src="jquery.touchwipe.1.1.1.js"></script>

Code to add :

$("#slides").touchwipe({
    wipeLeft: function() {  
    $('.next').trigger('click');  
    },
    wipeRight: function() { 
    $('.prev').trigger('click');
    },
    min_move_x: 20,
    min_move_y: 20,
    preventDefaultEvents: true
    });

**Comment by nicinabox** [comment]
Thanks @iveenano. This code doesn't belong in the plugin, however. If you want to add touch support like this, add it to your app with superslides included before it.
