### ISSUE TITLE
BG images are loaded multiple times and white sceen before animating

### ISSUE THREAD

**Issue by mikelsons** [nicinabox/superslides#71]
I started using Superslides.js ( v0.5.2 - 2013-01-20 ) version and it worked really well, but then i discovered before changing slide ( for example calling $slide.superslides('animate', 5); )    white screen appeared before animation on desktop safari and on ipad it happens on chrome as well.  I thought maybe switching to beta version maybe could solve it and it actually did ( Superslides - v0.5.4-beta - 2013-04-02 ). The white flickering disappeared and the transition was smooth. But new problems came with v0.5.4-beta. When it loads page it loads background images multiple times resulting in page being more heavier then it was  ( Went from ~2 MB to ~15MB ) and as well loading some none existing images. 

Could you maybe just tell what did you change in - v0.5.4-beta that flickering disappeared and i could alter my v0.5.2 version file so it loads normally and slides without white screen? 

Sceenshoots about multiple loads - you can see it loads kontakti.jpg multiple times by adding parameter ?1366....  : 

![Screen Shot 2013-04-18 at 5 52 10 PM](https://f.cloud.github.com/assets/1305248/397279/99838082-a83a-11e2-971e-e36ddd379c42.png)

Sceenshoots about requesting undefinied image:
![Screen Shot 2013-04-18 at 5 50 39 PM](https://f.cloud.github.com/assets/1305248/397282/a290af10-a83a-11e2-9d29-c3e639edd733.png)

**Comment by nicinabox** [comment]
Fixed in 0.6.0-beta2
