### ISSUE TITLE
fairly slow load

### ISSUE THREAD

**Issue by oohtruck** [nicinabox/superslides#72]
it's taking me about 5 seconds to load superslides on the initial page load, any ideas how i can troubleshoot this? i'm loading 5 images, about 150k each. compared to the demo load, this is taking eons. any ideas?

**Comment by oohtruck** [comment]
any ideas on this?

**Comment by nicinabox** [comment]
There might be a double image load going on. That could be affecting your performance.

**Comment by oohtruck** [comment]
how can i tell if that's what is actually happening?

**Comment by nicinabox** [comment]
Open web inspector and watch network requests as the page loads. Compare to [the demo](http://nicinabox.github.io/superslides/). It has pretty good performance.

**Comment by oohtruck** [comment]
so if that was happening, how can i fix? thanks!

**Comment by nicinabox** [comment]
Let's figure out what's actually happening first, then we can address the problem as it exists.

**Comment by oohtruck** [comment]
yep, looks like it's loading twice. in web inspector, it's showing doubles of all the slide images.

**Comment by nicinabox** [comment]
Nailed it. What version of superslides are you using?

**Comment by oohtruck** [comment]
v0.5.4-beta

**Comment by oohtruck** [comment]
that's what's in jquery.superslides.js, that is

**Comment by nicinabox** [comment]
[Try 0.5.2](https://github.com/nicinabox/superslides/archive/0.5.2.zip) and see if that changes anything.

**Comment by oohtruck** [comment]
OK. I switched it out and it looks like it's only loading the images once now. I feel like it loads a little quicker, however it's still slower than i'd like. Any other tips?

**Comment by nicinabox** [comment]
Hmm, you could try optimizing the images further. 150k each is pretty decent I'd say. Not sure what your hosting environment is like. How does it compare against the demo> I'm seeing about 1.1s on load and those images are in the 200-400 range.

**Comment by nicinabox** [comment]
Might also be helpful to watch the timeline to see what's getting hung up. Are you waiting for dependencies or libs or anything?

**Comment by oohtruck** [comment]
i'm hosting it on Shopify, which is for ecommerce stores. It's taking about 2.1 seconds to load right now, with 6 images all around 150k.

not sure if i'm reading timeline correctly, but it certainly looks like it's spending a lot of time on jquery.superslides.min.js

**Comment by nicinabox** [comment]
Is there something I could view?

**Comment by oohtruck** [comment]
sure: http://xxx.myshopify.com/

**Comment by nicinabox** [comment]
Here's what I see:

33 of 51 requests are images
1.6 of 1.9 MB are images

The biggest hangups I see are images coming from Shopify (newroll_x.jpg) in which they are blocked from downloading until other things complete. You're losing almost a full second right there.

**Comment by oohtruck** [comment]
ahh. gotcha! so it's just something i have to deal with when using Shopify and this, yeah?

**Comment by nicinabox** [comment]
Also, [you may not be the only one](http://ecommerce.shopify.com/c/shopify-discussion/t/cdn-is-very-very-slow-109964) experiencing this.

**Comment by nicinabox** [comment]
I'm not super familiar with Shopify's environment though. You might try testing a few different things. You could try removing the slider then check the load. Or maybe try ajax loading parts of it alleviate the initial load. It it is truly an issue with their CDN, you'd need to look at some additional techniques or revising your design to work around these constraints.

**Comment by nicinabox** [comment]
Double load fixed in 0.6.0
