### ISSUE TITLE
centering image

### ISSUE THREAD

**Issue by n2nn2n** [nicinabox/superslides#74]
Just discovered your slider..its exactly what I needed . simple.

However, as a note, I was using the latest stable release v0.5.4-beta - 2013-04-02 and found that on iPad, the image does not center, often times, on initial load, Once you touch the navigation it shifts back correctly. Also, it won't recenter automatically when going from landscape to portrait.

I switched back to version v0.5.2 - 2013-01-20 and all seems to work

Thanks for the great slider.
N2

**Comment by nicinabox** [comment]
I'll need to do some additional testing on iPad. Pull requests always welcome.

**Comment by nicinabox** [comment]
Image position has been reworked to function like `background-size: cover`. This will be released in 0.6.0, currently on master.

**Comment by chrisbradleyrun** [comment]
Hey -  Similar to the slider behaving like background-size: cover, is there a way to control background-position for individual images. Some images I would like to position left, and others right. 

Thanks
