### ISSUE TITLE
superslides custom pagination

### ISSUE THREAD

**Issue by lyndsaycrowther** [nicinabox/superslides#75]
Hi All,

I need help customizing this plugin so that the pagination looks like links with text in them instead of like the default.

So basically the output on the page should be: test1 | test2 | test3 ,etc. Any help would be much appreciated as I have been struggling with it.

Thanks

**Comment by neoone256** [comment]
Hi, I would change current css for .slides-pagination to this:

.slides-pagination a {
 width: 12px;
 height: 12px;
 vertical-align: middle;
 *vertical-align: auto;
 zoom: 1;
 margin: 20px;
 overflow: hidden;
 text-indent: -100%;
}

And the current is up to you... Remember to change also what is in line 378 (in the js) to this: 'text': 'test' + href

I hope this works for you. :D

**Comment by naPalmqvist** [comment]
Du you know a way to change Superslides pagination? Instead of bullits I would like: START   PORTFOLIO   CONTACT.

**Comment by nicinabox** [comment]
Don't use the built in pagination. Just create your own links and go to a slide when you click on them.

**Comment by naPalmqvist** [comment]
Sounds so easy Nicinabox. But I don't get it?

**Comment by nicinabox** [comment]
It really is. Use the href to go link to a slide.

**Comment by naPalmqvist** [comment]
I'm half way there! Check slide 5. It directs back to slide 2.
http://superfresh.se/projects/superslides-0.6.2/examples/touch.html#5

**Comment by nicinabox** [comment]
See there!

**Comment by naPalmqvist** [comment]
I think I know what you first said. I use the "absolute position" for my links instead of the bullits. Thanks!

**Comment by naPalmqvist** [comment]
Hi, it's me again. Sorry. But I've tried to make a.current mark the current slide in my <ul> navigation. I've googled as hell but can't figure it out.

Here's where I am:
http://superfresh.se/projects/superslides-0.6.2/examples/touch.html#first-slide

**Comment by nicinabox** [comment]
Something like this. All of this is documented in the API.

``` javascript
$('#slides').on('animated.slides', function() { 
  var current_index = $(this).superslides('current');
  $('.navigation li').removeClass('current');
  $('.navigation li').eq(current_index).addClass('current');
});
```
