### ISSUE TITLE
Destroy superslides and re-init

### ISSUE THREAD

**Issue by benjbdev** [nicinabox/superslides#78]
If i destroy a slide and init it just after, the previous "slides-control" wrapper is not deleted.

Each times a new "slides-control" wrapper comes wrap the other "slides-control" wrapper !

**Comment by benjbdev** [comment]
Please help.... I developed all my client website with this slider... and there is too much problems................................................................................... damn...

**Comment by benjbdev** [comment]
I don't want to change the slider and rebuild the website..

**Comment by benjbdev** [comment]
Don't propose opensources plugins if you don't do support and propose versions with tons of problems.

**Comment by zoltanseer** [comment]
after more than a year, i would say that if you are a developer, you can try to fix it yourself. Opensource gives the possibility to the community to make the product even better.

**Comment by MaicolBen** [comment]
This is the way I found (not very clean but it works) to destroy the plugin (and then restart without problems):

```
$('.mySlideDiv').superslides('destroy');
$('.slides-pagination').remove(); // remove pagination
var imgs = $('.slides-control').find('img');
$('.slides-control').remove(); // remove html generated for superslides
$('.mySlideDiv').prepend('<div class="slides-container"></div>');
// leave the div with the images as before starting the plugin
$('.slides-container').prepend(imgs); 
```
