### ISSUE TITLE
Safari and last slide, page breaks

### ISSUE THREAD

**Issue by paulfehr** [nicinabox/superslides#79]
I made a short video to show what happens:
https://dl.dropboxusercontent.com/u/8337639/Untitled.m4v

Basically, if you advance through all the slides, when you reach the last one everything breaks.  This only happens (from what I've found) on Safari, on both Mac and Windows.
It seems that it gets fixed when you resize the window, but only on Windows. (Mac is Safari 6.0.4, Windows is 5.7)

Site is this:
http://folklore.mx/paul/demo.php

**Comment by carlosbergen** [comment]
If you remove the required autofocus of your first input field in your contact form it will stop breaking.

**Comment by paulfehr** [comment]
Thanks carlosbergen :)
That worked.
