### ISSUE TITLE
Firefox 14.0.1 on Windows 7

### ISSUE THREAD

**Issue by timdenee** [nicinabox/superslides#8]
Hello, any advice on Firefox compatibility?  I'm testing in Firefox 14.0.1 on Windows 7 and I can't get any of the slide content to show, just the navigation buttons. I have the same problem trying to access the demo site (http://nicinabox.github.com/superslides/). Any ideas? It works fine in Chrome and IE.

**Comment by nicinabox** [comment]
Confirmed. Seeing it on FF 14.0.1 on OSX as well.

**Comment by nicinabox** [comment]
~~This seems to be related to jQuery 1.8~~, but I'm looking for a workaround.

Actually related to jQuery Animate Enhanced plugin. https://github.com/benbarnett/jQuery-Animate-Enhanced/issues/94

**Comment by nicinabox** [comment]
Plugin has been fixed.
