### ISSUE TITLE
Conflict with jQuery 1.8 and 1.9.1

### ISSUE THREAD

**Issue by robinwkurtz** [nicinabox/superslides#86]
I'm having an issue with using Superslider (Fantastic btw, Thank You!) with another jQuery plugin. My second plugin uses jQuery 1.9.1 and when linked to my page superslider does not load it's images. I've tried using the jQuery Migration to make superslider use 1.9.1 but have had no seeing as I am at the utmost beginner level of script beyond html and css.

Does anyone have any solutions for this? Thanks in advanced

**Comment by nicinabox** [comment]
Unfortunately I've had compatibility issues with jQuery 1.9 and haven't had time to address them. I recommend using 1.8 for the time being.

**Comment by nicinabox** [comment]
0.6.0 is compatible with jQuery 1.9.
