### ISSUE TITLE
Creating one slide. 

### ISSUE THREAD

**Issue by Nerdinvasion** [nicinabox/superslides#87]
Greetings 

I am building a whole website with this superslider "Framework". The 1st phase of the site is the underconstruction page which needs only one slide. I have tried commenting out the other slides but the whole website breaks. How do I cancel out the other slides without breaking the whole framework?

**Comment by nicinabox** [comment]
The latest tagged version should work fine with a single slide. But if you're just wanting a single full screen image, you don't need the overhead that this javascript provides. You can do that with just CSS.

**Comment by Nerdinvasion** [comment]
Greetings 

I will be honest I was a bit lazy there but i finally got it. All i hade to do was to comment out the images for slide two. I noticed that they are not added onto the <li></li> tags. 

The reason why I'm using superslider for the under-construction is that the backend guy wants to just finish with the site at once, so since the slider is a great framework for building what we want i though i could just code the front end for the full site and just comment out the stuff we don't need for the 1st phase of the project. The site has a whole campaign around the under-construction page. 

Thanks

**Comment by nicinabox** [comment]
Sounds like you got it under control then :)
