### ISSUE TITLE
Page loaded by ajax, slider not showing

### ISSUE THREAD

**Issue by gnrocks** [nicinabox/superslides#9]
Hello !
First of all, thank you for this wonderful and simple plugin, i am very lucky to have stumbled upon it !

I am having an issue now, and i hope you could guide me or help me with it.

I have a completely ajaxed website. When i first load a page that contains the slider, it shows fine. Then when i move to another page, and come back, the slider does not show.

I inspected the css, and it seems that "display:none" is added to the list and container. I also tried to play around with the code, but i got lost. I saw a variable called "first_load", that might be the origin of my issue.

I tried the callback superslides.start, but it does not work. Is there a way to disable the "first_load" option or destroy the slider when the page changes ?

Regards

**Comment by nicinabox** [comment]
Currently it doesn't support ajax loading or appending items. I've had a few requests for this now, so I'm thinking it's something I should add in the next version.

**Comment by gnrocks** [comment]
Hello,

I am sorry i didn't explain myself well.

It is the page that contains the slider that is loaded by ajax. Usually, when a new page is loaded, the DOM is reset. Now when i load a page that contains the slider by ajax, the slider does not show because i think there is a variable (first_load) that says the slider is already active.

Do you know a way to reset this variable or completely destroy the slider ?

Regards,

**Comment by nicinabox** [comment]
Ahh. When you load your page, initialize the slider at the same time.

**Comment by gnrocks** [comment]
Thank you for your quick reply !

I have tried this (maybe i missed a step) : 

var init_scripts = function() {
   $('#slides').superslides();
   $('body').on('slides.initialized', '#slides', function(){
      console.log('Superslides initialized')
   })
}

Then 

$('.link').live('click', function() {
   $('#content').load(url, function() {
      init_scripts();
   });
});

This is not the complete code, i can send it to you when i get home.
What happens is that the first time i load a page that contains the slider, i can see the message in the console. When i reopen this page (or another that contains the slider), the script above is supposed to reinitialize the slider, but i do not see the message in the console again.

I am reinitializing the slider correctly ? Is there a way to disable the first_load option (i tried removing some lines that contain this variable but the script crashed) ?

Thank you again for your time, this is really appreciated !

**Comment by nicinabox** [comment]
That seems like it _should_ work. I'll dig into it in a few hours when I get home.

**Comment by gnrocks** [comment]
Thank you again for your time !
I will check it again and if necessary set up a test drive online for you so you can easily inspect it.
Thanks again !

**Comment by nicinabox** [comment]
That will be very helpful!

**Comment by nicinabox** [comment]
I made up a testbed with the bits you posted above. It loads correctly for me. It's possible you have some other code interfering. If you could post up a more demo somewhere that replicates your problem, I'll have a look at it.
