### ISSUE TITLE
Highlighting Slide Navc

### ISSUE THREAD

**Issue by bauds** [nicinabox/superslides#91]
Hello There,

In order to control the slides I am using the following custom links. When i click the Slide 2 link for instance, it does not highlight the text and register that we are now on slide 2. Is there something extra i should be doing to achieve this  

```
     <ul class="nav">
            <li><a href="#0">Slide 1</a></li>
            <li><a href="#1">Slide 2</a></li>
            <li><a href="#2">Slide 3</a></li>
            <li><a href="#3">Slide 4</a></li>
        </ul>
```

Thanks

**Comment by nicinabox** [comment]
Custom pagination is not supported out of the box. You'll need you write your own logic for setting the state on each pagination if you opt not to use the built in one.
