### ISSUE TITLE
Fade in navigation buttons

### ISSUE THREAD

**Issue by bauds** [nicinabox/superslides#93]
Hello, I have set the navigation arrows (left & right) to display none in css. When the first image loads i want to fade them in. Even with the css set to display none and the below fade in scrip they always appear on entrance to the site..? Are they controlled somewhere else..?

``` javascript
$(document).on('init.slides', function() {

    $('.loading-container').fadeOut(function() {
      $(this).remove();
      });

    $('.slides-navigation').fadeIn(100);

  });
```

**Comment by nicinabox** [comment]
Pagination is appended during initialization. Try setting it to `display: none` in your css first, then fading in after it's initialized.

**Comment by bauds** [comment]
That is what th above does. I have set them to display none but they are always visible..?
The css class i am using is .slides-navigation and this is set to display none. Any ideas why they still display..?
