### ISSUE TITLE
'Pause on Hover'?

### ISSUE THREAD

**Issue by danny-englander** [nicinabox/superslides#96]
Hi I am wondering if there is a "pause on hover" option. I am guessing this might be a feature request. Right now I have:

`play: 5000`

... set to auto advance the slides and that works nicely but the pause on hover function would also be nice. 

Thanks.

**Comment by NunoBentes** [comment]
I was looking for something like that!!!! Any way to do it with the current API?

**Comment by nicinabox** [comment]
Yes, listen for mouseover and mouseout events then stop/start the slides with the API. Easy peasy.

**Comment by danny-englander** [comment]
Do you have any code examples? That would be great, thanks.

**Comment by nicinabox** [comment]
``` javascript
$('#slides').on('mouseenter', function() {
  $(this).superslides('stop');
});
$('#slides').on('mouseleave', function() {
  $(this).superslides('start');
});
```

**Comment by danny-englander** [comment]
Thank you, I'll give that a try!

**Comment by NunoBentes** [comment]
Many thanks!!!! :) It works like a charm!!!!

**Comment by Third-Hyperion** [comment]
Hi when using the code mentioned by nicinabox, if you hover over the slide yes it does stop however as soon as you move the cursor off the slide it instantly changes, and if you flick the cursor on and off the slide it changes every time, so it doesn't take into consideration the time before next slide. 

Is there anyway to stop this? and pause the time till the next slide is shown. For example the slide takes 5 seconds normally to slide from one to another, after one second you hover onto the slide pausing it leaving 4 seconds remaining, when you take the cursor back off the slide.. let the counter start where it left off and countdown a further 4 seconds before changing slide?

Thanks.

**Comment by doav** [comment]
@wesearl91: To prevent the slide from changing on every in-out movement, you can use a timer, like so:

``` javascript
var hoverTimer = 0; 
$(document).on('mouseenter', function() {
    $slides.superslides('stop');
    clearTimeout(hoverTimer);
});
$(document).on('mouseleave', function() {
    hoverTimer = setTimeout(function(){
        $slides.superslides('start');
    }, 2000); 
});
```

After examining your content for a while, user will realize that the slide is on pause. At this point, it is likely that she has lost track of pausing time, and has been expecting the next slide for a little while. So she will click to move on to the next one. If she move her cursor out of this fullscreen slide to let it autoplay, I think we should wait for just a little (3-4 seconds remaining time are too long) and resume sliding.

**Comment by ergec** [comment]
This is my solution to @nicinabox code to prevent instant slide change on mouseleave. Plugin's start method needs to be altered as follows

```
start: function() {
    var that = this;
    if (that.options.hashchange) {
      $(window).trigger('hashchange');
    } else if (!this.inited) {
      this.animate();
      this.inited = true;
    }
    ...
    ...
}
```

**Comment by minstyle** [comment]
This is my working solution for Superslides - v0.6.3-wip - 2013-12-17.

```
var $slides = $('#slides');

$slides.superslides({
   animation: 'fade',
   animation_speed: 350,
   play: 5000
});

// Pause Slider on Mouseover
var sliderTimeout;

$slides.on('mouseenter', function() {
   clearTimeout(sliderTimeout);
   $(this).superslides('stop');
});

$slides.on('mouseleave', function() {
   sliderTimeout = setTimeout(function() { $slides.superslides('start'); }, 5000);
});
```
