### ISSUE TITLE
Minor alterations request - will pay

### ISSUE THREAD

**Issue by bauds** [nicinabox/superslides#97]
Hi Nicinabox,

I have tried to build in a few minor alterations with out success. I would be looking to pay you for your time.

If you are interested please can you send me an email to obaudains@googlemail.com and i can send you my requests before you quote..?

Many Thanks

**Comment by bauds** [comment]
Hi Nic,

I sent an email last night..... please confirm receipt (You dont appear to have received the ones sent last friday..?)

**Comment by nicinabox** [comment]
Huh, I wonder if we aren't getting each others emails. I did get an email from you about 6 hours ago.
